package com.raphaowl.dnd.enums;

import static com.raphaowl.dnd.enums.FoodAndDrink.PriceLevel.COPPER;
import static com.raphaowl.dnd.enums.FoodAndDrink.PriceLevel.GOLD;
import static com.raphaowl.dnd.enums.FoodAndDrink.PriceLevel.SILVER;
import static com.raphaowl.dnd.enums.TavernCuisine.*;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum FoodAndDrink {
    // ---------------------------------------------------------------------------------
    // BEBIDAS COMUNS (PHB Price List)
    // ---------------------------------------------------------------------------------
    WATER_FREE(0, COPPER, DRINKS),
    SMALL_BEER(1, SILVER, DRINKS),
    BARK_TEA(1, SILVER, DRINKS),
    ALE_STRONG(5, SILVER, DRINKS),
    WINE_TAVERN(5, SILVER, DRINKS),
    HONEY_MEAD(1, GOLD, DRINKS),

    // ---------------------------------------------------------------------------------
    // COMIDA COMUM (Modest / Comfortable - 3sp a 8sp)
    // ---------------------------------------------------------------------------------
    GRILLED_WILD_BOAR_CHOPS(3, SILVER, COMMON_FAERUNIAN),
    BROILED_SALMON_POTATOES(3, SILVER, COMMON_FAERUNIAN),
    ROAST_CHICKEN_POTATOES_MODEST(3, SILVER, COMMON_FAERUNIAN),
    SMOKED_SAUSAGE_EGGS_DATES(3, SILVER, COMMON_FAERUNIAN),
    CHEESE_PIE_ONION_SOUP(3, SILVER, COMMON_FAERUNIAN),
    BAKED_BOAR_GREENS(3, SILVER, COMMON_FAERUNIAN),
    MINTED_PEA_SOUP(3, SILVER, COMMON_FAERUNIAN),
    BAKED_GOAT_FLANK(3, SILVER, COMMON_FAERUNIAN),
    RABBIT_STEW_CRACKERS(3, SILVER, COMMON_FAERUNIAN),
    LEMMING_BERRY_SOUP(3, SILVER, COMMON_FAERUNIAN),

    // ---------------------------------------------------------------------------------
    // COMIDA ARISTOCRÁTICA (ARISTOCRATIC_HALL) - (Geralmente 2gp a 4gp)
    // ---------------------------------------------------------------------------------
    ROAST_STAG_ANTLER_SAUCE(4, GOLD, ARISTOCRATIC_HALL),
    POACHED_PEPPERED_QUAIL_EGGS(4, GOLD, ARISTOCRATIC_HALL),
    SPICED_MONKEY_TAIL(4, GOLD, ARISTOCRATIC_HALL),
    ROAST_HERON_SUNDEW(4, GOLD, ARISTOCRATIC_HALL),
    LOBSTER_CREAM_SAUCE(4, GOLD, ARISTOCRATIC_HALL),
    CRAB_STUFFED_LOBSTER_TAIL(4, GOLD, ARISTOCRATIC_HALL),
    ROAST_PHEASANT_OYSTER(4, GOLD, ARISTOCRATIC_HALL),
    POACHED_DUCK_FARRO(2, GOLD, ARISTOCRATIC_HALL),
    FRIED_OSTRICH_OMELET(2, GOLD, ARISTOCRATIC_HALL),

    // ---------------------------------------------------------------------------------
    // COMIDA MONSTRUOSA (MONSTROUS_SPECIALTIES) - (Preço base 5cp a 8cp)
    // ---------------------------------------------------------------------------------
    CRUNCHY_CRITTERS_PUDDING(5, COPPER, MONSTROUS_SPECIALTIES),
    SMASHED_GUTS_CABBAGE(5, COPPER, MONSTROUS_SPECIALTIES),
    SOURED_GOAT_MILK_RICE(7, COPPER, MONSTROUS_SPECIALTIES),
    FRIED_CHUNK_LARD_BREAD(7, COPPER, MONSTROUS_SPECIALTIES),
    SALTED_EYES_CARROT_ENDS(6, COPPER, MONSTROUS_SPECIALTIES),
    BONE_AND_BLOOD_STEW(8, COPPER, MONSTROUS_SPECIALTIES),
    LIVER_LUNG_PIE(8, COPPER, MONSTROUS_SPECIALTIES),

    // ---------------------------------------------------------------------------------
    // COMIDA SUBTERRÂNEA (Underdark)
    // ---------------------------------------------------------------------------------
    FLUORESCENT_FUNGUS_SALAD(3, SILVER, UNDERDARK_DELICACIES),
    DICED_BLIND_EEL(5, SILVER, UNDERDARK_DELICACIES),
    AMBER_LICHEN_BREAD(4, SILVER, UNDERDARK_DELICACIES),
    TRANSLUCENT_CRAYFISH_STEW(6, SILVER, UNDERDARK_DELICACIES),
    CRIMSON_MOSS_CAKES(5, SILVER, UNDERDARK_DELICACIES),
    CRUSTACEAN_BROTH_IRONLOAF(7, SILVER, UNDERDARK_DELICACIES), // Novo
    ROASTED_DEEP_BEETLES(6, SILVER, UNDERDARK_DELICACIES),
    TOASTED_SALAMANDER(7, SILVER, UNDERDARK_DELICACIES),
    ARACHNIDUMPLINGS_FUNGUS(8, SILVER, UNDERDARK_DELICACIES),
    TOADSTOOL_STEAK(9, SILVER, UNDERDARK_DELICACIES),
    LOBE_OF_GRELL(1, GOLD, UNDERDARK_DELICACIES),
    ROTHE_STEAK(8, SILVER, UNDERDARK_DELICACIES),
    COOKED_INTELLECT_DEVOURER(1, GOLD, UNDERDARK_DELICACIES),

    // ---------------------------------------------------------------------------------
    // COMIDA ÉLFICA (ELVEN_FOREST_FARE) - Geralmente Modest (3sp) a Comfortable (8sp)
    // ---------------------------------------------------------------------------------
    // Vegetais
    ELVEN_CRESS(3, SILVER, ELVEN_FOREST_FARE),
    ELVEN_LEEK_CHIVES(3, SILVER, ELVEN_FOREST_FARE),
    ELVEN_GREENSPEAR(5, SILVER, ELVEN_FOREST_FARE),
    ELVEN_COUSHOOTS(4, SILVER, ELVEN_FOREST_FARE),
    ELVEN_BROWNBUDS(3, SILVER, ELVEN_FOREST_FARE),

    // Frutas
    ELVEN_BERRY_BLEND(4, SILVER, ELVEN_FOREST_FARE),
    ELVEN_ROSEAPPLE(5, SILVER, ELVEN_FOREST_FARE),
    ELVEN_AELFENGRAPE_FRUIT(8, SILVER, ELVEN_FOREST_FARE),

    // Sopas (Frias)
    ELVEN_LEEK_SOUP_COLD(5, SILVER, ELVEN_FOREST_FARE),
    ELVEN_DARBLALATHA_SOUP(6, SILVER, ELVEN_FOREST_FARE),
    ELVEN_BLACKBARK_STEW(8, SILVER, ELVEN_FOREST_FARE),
    ELVEN_HAENDUR_WORMS(10, SILVER, ELVEN_FOREST_FARE),

    // Carnes e Peixes (Geralmente Comfortable/Wealthy)
    ELVEN_SEARED_RABBIT(8, SILVER, ELVEN_FOREST_FARE),
    ELVEN_THAENWING(10, SILVER, ELVEN_FOREST_FARE),
    ELVEN_SORNSTAG_VENISON(1, GOLD, ELVEN_FOREST_FARE),
    ELVEN_SILVEREYES_STEW(8, SILVER, ELVEN_FOREST_FARE),
    ELVEN_SURKYL_BEAVER(1, GOLD, ELVEN_FOREST_FARE),

    // Comida de Trilha
    ELVEN_MINTNUT_CHEESE(5, SILVER, ELVEN_FOREST_FARE),
    ELVEN_TAECE_FISH(4, SILVER, ELVEN_FOREST_FARE),
    ELVEN_MARRUTH_PIES(6, SILVER, ELVEN_FOREST_FARE),

    // Sobremesas e Bebidas
    ELVEN_MINT_JELLY(4, SILVER, ELVEN_FOREST_FARE),
    ELVEN_BERRY_TARTS(5, SILVER, ELVEN_FOREST_FARE),
    ELVEN_SPRUCEBARK_QUAFF(2, SILVER, ELVEN_FOREST_FARE),
    ELVEN_MINTWATER(1, SILVER, ELVEN_FOREST_FARE),

    // ---------------------------------------------------------------------------------
    // COMIDA EXÓTICA (Monstros)
    // ---------------------------------------------------------------------------------
    SHIFTING_CALAMARI(25, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    FAJITA_NOCTURNA(18, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    UP_AND_DOWN_STEW(35, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    STEAMED_UMBER_HULK(20, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    UNDERDARK_PAELLA(30, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    KING_SEA_SASHIMI(50, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    GORGON_ROAST(40, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    HYDRA_EGGS(55, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    TADPOLE_COCKTAIL(60, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    GRIFFIN_GYRO_WRAP(45, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    DRYAD_TEA(15, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    BONFIRE_DIRE_BOAR(35, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    MARAUDERS_PIE(18, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    MUSHROOM_CASSEROLE(10, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    SKEWERED_MANTICORE(28, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    ESCARFLEAU(32, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    DRACONIC_JERKY(60, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    BULLYWUG_SUR_LA_FLAMME(12, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    HIPPOCAMPUS_SURF_N_TURF(22, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    GELATINOUS_MARMALADE(15, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    WOODLAND_BITE(18, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    LIGHTNING_GUMBO(45, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    FEAST_OF_GRUUMSH(30, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    LOST_HONOR(10, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    TROLL_TATERS(15, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    GNOLL_ROLLS(8, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    PHOENIX_ROAST(75, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    SLICED_TROLL_LIVER(20, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    DESERT_SUN_JERKY(12, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    BEHOLDER_SUSHI(70, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    SAHAGUIN_ROE(30, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    PAN_FRIED_COCKATRICE(20, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    KRAKEN_CAVIAR(100, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    OWLBEAR_STEAK(15, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    ROAST_BEHIR(40, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    SHELL_SHARK_FIN_SOUP(15, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    MIND_FLAYER_CALAMARI(50, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    TERRASQUE_ICE_CREAM(90, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    BULLETE_FIN_SOUP(35, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    ILITHARI(65, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    POACHED_BASILISK_EYE(40, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    ANIMATED_HORS_DOEUVRES(25, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    ROCHE_FOIE_GRAS(80, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    QUASIT_BOIL(18, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    FONDGOO(30, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    FOREVER_STEW(15, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    BASILISK_BISQUE(35, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    ALMIRAJ_RABBIT_BUCHADA(25, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    FLUMPH_UNDERSALMON(45, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    NEOGI_NECK(12, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    PARTY_MEAT(10, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    HONEYED_SIRENS_TONGUE(50, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES),
    WATER_ELEMENTAL_JUICE(15, SILVER, TavernCuisine.MONSTROUS_SPECIALTIES);

    // --- Campos do Enum ---
    private final int basePrice;
    private final PriceLevel priceUnit;
    private final TavernCuisine cuisineType;

    // Enum helper para a unidade de preço
    @Getter
    @AllArgsConstructor
    public enum PriceLevel {
        COPPER("copper-bg"),
        SILVER("silver-bg"),
        GOLD("gold-bg");

        private String color;
    }
}
