package com.raphaowl.dnd.enums;

import java.util.stream.Stream;

import com.fasterxml.jackson.annotation.JsonCreator;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum MonsterNameEnum {
    ABOLETH("aboleth", "Aboleth"),
    ACOLYTE("acolyte", "Acolyte"),
    ADULT_BLACK_DRAGON("adult-black-dragon", "Adult Black Dragon"),
    ADULT_BLUE_DRAGON("adult-blue-dragon", "Adult Blue Dragon"),
    ADULT_BRASS_DRAGON("adult-brass-dragon", "Adult Brass Dragon"),
    ADULT_BRONZE_DRAGON("adult-bronze-dragon", "Adult Bronze Dragon"),
    ADULT_COPPER_DRAGON("adult-copper-dragon", "Adult Copper Dragon"),
    ADULT_GOLD_DRAGON("adult-gold-dragon", "Adult Gold Dragon"),
    ADULT_GREEN_DRAGON("adult-green-dragon", "Adult Green Dragon"),
    ADULT_RED_DRAGON("adult-red-dragon", "Adult Red Dragon"),
    ADULT_SILVER_DRAGON("adult-silver-dragon", "Adult Silver Dragon"),
    ADULT_WHITE_DRAGON("adult-white-dragon", "Adult White Dragon"),
    AIR_ELEMENTAL("air-elemental", "Air Elemental"),
    ANCIENT_BLACK_DRAGON("ancient-black-dragon", "Ancient Black Dragon"),
    ANCIENT_BLUE_DRAGON("ancient-blue-dragon", "Ancient Blue Dragon"),
    ANCIENT_BRASS_DRAGON("ancient-brass-dragon", "Ancient Brass Dragon"),
    ANCIENT_BRONZE_DRAGON("ancient-bronze-dragon", "Ancient Bronze Dragon"),
    ANCIENT_COPPER_DRAGON("ancient-copper-dragon", "Ancient Copper Dragon"),
    ANCIENT_GOLD_DRAGON("ancient-gold-dragon", "Ancient Gold Dragon"),
    ANCIENT_GREEN_DRAGON("ancient-green-dragon", "Ancient Green Dragon"),
    ANCIENT_RED_DRAGON("ancient-red-dragon", "Ancient Red Dragon"),
    ANCIENT_SILVER_DRAGON("ancient-silver-dragon", "Ancient Silver Dragon"),
    ANCIENT_WHITE_DRAGON("ancient-white-dragon", "Ancient White Dragon"),
    ANDROSPHINX("androsphinx", "Androsphinx"),
    ANIMATED_ARMOR("animated-armor", "Animated Armor"),
    ANKHEG("ankheg", "Ankheg"),
    APE("ape", "Ape"),
    ARCHMAGE("archmage", "Archmage"),
    ASSASSIN("assassin", "Assassin"),
    AWAKENED_SHRUB("awakened-shrub", "Awakened Shrub"),
    AWAKENED_TREE("awakened-tree", "Awakened Tree"),
    AXE_BEAK("axe-beak", "Axe Beak"),
    AZER("azer", "Azer"),
    BABOON("baboon", "Baboon"),
    BADGER("badger", "Badger"),
    BALOR("balor", "Balor"),
    BANDIT("bandit", "Bandit"),
    BANDIT_CAPTAIN("bandit-captain", "Bandit Captain"),
    BARBED_DEVIL("barbed-devil", "Barbed Devil"),
    BASILISK("basilisk", "Basilisk"),
    BAT("bat", "Bat"),
    BEARDED_DEVIL("bearded-devil", "Bearded Devil"),
    BEHIR("behir", "Behir"),
    BERSERKER("berserker", "Berserker"),
    BLACK_BEAR("black-bear", "Black Bear"),
    BLACK_DRAGON_WYRMLING("black-dragon-wyrmling", "Black Dragon Wyrmling"),
    BLACK_PUDDING("black-pudding", "Black Pudding"),
    BLINK_DOG("blink-dog", "Blink Dog"),
    BLOOD_HAWK("blood-hawk", "Blood Hawk"),
    BLUE_DRAGON_WYRMLING("blue-dragon-wyrmling", "Blue Dragon Wyrmling"),
    BOAR("boar", "Boar"),
    BONE_DEVIL("bone-devil", "Bone Devil"),
    BRASS_DRAGON_WYRMLING("brass-dragon-wyrmling", "Brass Dragon Wyrmling"),
    BRONZE_DRAGON_WYRMLING("bronze-dragon-wyrmling", "Bronze Dragon Wyrmling"),
    BROWN_BEAR("brown-bear", "Brown Bear"),
    BUGBEAR("bugbear", "Bugbear"),
    BULETTE("bulette", "Bulette"),
    CAMEL("camel", "Camel"),
    CAT("cat", "Cat"),
    CENTAUR("centaur", "Centaur"),
    CHAIN_DEVIL("chain-devil", "Chain Devil"),
    CHIMERA("chimera", "Chimera"),
    CHUUL("chuul", "Chuul"),
    CLAY_GOLEM("clay-golem", "Clay Golem"),
    CLOAKER("cloaker", "Cloaker"),
    CLOUD_GIANT("cloud-giant", "Cloud Giant"),
    COCKATRICE("cockatrice", "Cockatrice"),
    COMMONER("commoner", "Commoner"),
    CONSTRICTOR_SNAKE("constrictor-snake", "Constrictor Snake"),
    COPPER_DRAGON_WYRMLING("copper-dragon-wyrmling", "Copper Dragon Wyrmling"),
    COUATL("couatl", "Couatl"),
    CRAB("crab", "Crab"),
    CROCODILE("crocodile", "Crocodile"),
    CULT_FANATIC("cult-fanatic", "Cult Fanatic"),
    CULTIST("cultist", "Cultist"),
    DARKMANTLE("darkmantle", "Darkmantle"),
    DEATH_DOG("death-dog", "Death Dog"),
    DEEP_GNOME_SVIRFNEBLIN("deep-gnome-svirfneblin", "Deep Gnome (Svirfneblin)"),
    DEER("deer", "Deer"),
    DEVA("deva", "Deva"),
    DIRE_WOLF("dire-wolf", "Dire Wolf"),
    DJINNI("djinni", "Djinni"),
    DOPPELGANGER("doppelganger", "Doppelganger"),
    DRAFT_HORSE("draft-horse", "Draft Horse"),
    DRAGON_TURTLE("dragon-turtle", "Dragon Turtle"),
    DRETCH("dretch", "Dretch"),
    DRIDER("drider", "Drider"),
    DROW("drow", "Drow"),
    DRUID("druid", "Druid"),
    DRYAD("dryad", "Dryad"),
    DUERGAR("duergar", "Duergar"),
    DUST_MEPHIT("dust-mephit", "Dust Mephit"),
    EAGLE("eagle", "Eagle"),
    EARTH_ELEMENTAL("earth-elemental", "Earth Elemental"),
    EFREETI("efreeti", "Efreeti"),
    ELEPHANT("elephant", "Elephant"),
    ELK("elk", "Elk"),
    ERINYES("erinyes", "Erinyes"),
    ETTERCAP("ettercap", "Ettercap"),
    ETTIN("ettin", "Ettin"),
    FIRE_ELEMENTAL("fire-elemental", "Fire Elemental"),
    FIRE_GIANT("fire-giant", "Fire Giant"),
    FLESH_GOLEM("flesh-golem", "Flesh Golem"),
    FLYING_SNAKE("flying-snake", "Flying Snake"),
    FLYING_SWORD("flying-sword", "Flying Sword"),
    FROG("frog", "Frog"),
    FROST_GIANT("frost-giant", "Frost Giant"),
    GARGOYLE("gargoyle", "Gargoyle"),
    GELATINOUS_CUBE("gelatinous-cube", "Gelatinous Cube"),
    GHAST("ghast", "Ghast"),
    GHOST("ghost", "Ghost"),
    GHOUL("ghoul", "Ghoul"),
    GIANT_APE("giant-ape", "Giant Ape"),
    GIANT_BADGER("giant-badger", "Giant Badger"),
    GIANT_BAT("giant-bat", "Giant Bat"),
    GIANT_BOAR("giant-boar", "Giant Boar"),
    GIANT_CENTIPEDE("giant-centipede", "Giant Centipede"),
    GIANT_CONSTRICTOR_SNAKE("giant-constrictor-snake", "Giant Constrictor Snake"),
    GIANT_CRAB("giant-crab", "Giant Crab"),
    GIANT_CROCODILE("giant-crocodile", "Giant Crocodile"),
    GIANT_EAGLE("giant-eagle", "Giant Eagle"),
    GIANT_ELK("giant-elk", "Giant Elk"),
    GIANT_FIRE_BEETLE("giant-fire-beetle", "Giant Fire Beetle"),
    GIANT_FROG("giant-frog", "Giant Frog"),
    GIANT_GOAT("giant-goat", "Giant Goat"),
    GIANT_HYENA("giant-hyena", "Giant Hyena"),
    GIANT_LIZARD("giant-lizard", "Giant Lizard"),
    GIANT_OCTOPUS("giant-octopus", "Giant Octopus"),
    GIANT_OWL("giant-owl", "Giant Owl"),
    GIANT_POISONOUS_SNAKE("giant-poisonous-snake", "Giant Poisonous Snake"),
    GIANT_RAT("giant-rat", "Giant Rat"),
    GIANT_RAT_DISEASED("giant-rat-diseased", "Giant Rat (Diseased)"),
    GIANT_SCORPION("giant-scorpion", "Giant Scorpion"),
    GIANT_SEA_HORSE("giant-sea-horse", "Giant Sea Horse"),
    GIANT_SHARK("giant-shark", "Giant Shark"),
    GIANT_SPIDER("giant-spider", "Giant Spider"),
    GIANT_TOAD("giant-toad", "Giant Toad"),
    GIANT_VULTURE("giant-vulture", "Giant Vulture"),
    GIANT_WASP("giant-wasp", "Giant Wasp"),
    GIANT_WEASEL("giant-weasel", "Giant Weasel"),
    GIANT_WOLF_SPIDER("giant-wolf-spider", "Giant Wolf Spider"),
    GIBBERING_MOUTHER("gibbering-mouther", "Gibbering Mouther"),
    GLABREZU("glabrezu", "Glabrezu"),
    GLADIATOR("gladiator", "Gladiator"),
    GNOLL("gnoll", "Gnoll"),
    GOAT("goat", "Goat"),
    GOBLIN("goblin", "Goblin"),
    GOLD_DRAGON_WYRMLING("gold-dragon-wyrmling", "Gold Dragon Wyrmling"),
    GORGON("gorgon", "Gorgon"),
    GRAY_OOZE("gray-ooze", "Gray Ooze"),
    GREEN_DRAGON_WYRMLING("green-dragon-wyrmling", "Green Dragon Wyrmling"),
    GREEN_HAG("green-hag", "Green Hag"),
    GRICK("grick", "Grick"),
    GRIFFON("griffon", "Griffon"),
    GRIMLOCK("grimlock", "Grimlock"),
    GUARD("guard", "Guard"),
    GUARDIAN_NAGA("guardian-naga", "Guardian Naga"),
    GYNOSPHINX("gynosphinx", "Gynosphinx"),
    HALF_RED_DRAGON_VETERAN("half-red-dragon-veteran", "Half-Red Dragon Veteran"),
    HARPY("harpy", "Harpy"),
    HAWK("hawk", "Hawk"),
    HELL_HOUND("hell-hound", "Hell Hound"),
    HEZROU("hezrou", "Hezrou"),
    HILL_GIANT("hill-giant", "Hill Giant"),
    HIPPOGRIFF("hippogriff", "Hippogriff"),
    HOBGOBLIN("hobgoblin", "Hobgoblin"),
    HOMUNCULUS("homunculus", "Homunculus"),
    HORNED_DEVIL("horned-devil", "Horned Devil"),
    HUNTER_SHARK("hunter-shark", "Hunter Shark"),
    HYDRA("hydra", "Hydra"),
    HYENA("hyena", "Hyena"),
    ICE_DEVIL("ice-devil", "Ice Devil"),
    ICE_MEPHIT("ice-mephit", "Ice Mephit"),
    IMP("imp", "Imp"),
    INVISIBLE_STALKER("invisible-stalker", "Invisible Stalker"),
    IRON_GOLEM("iron-golem", "Iron Golem"),
    JACKAL("jackal", "Jackal"),
    KILLER_WHALE("killer-whale", "Killer Whale"),
    KNIGHT("knight", "Knight"),
    KOBOLD("kobold", "Kobold"),
    KRAKEN("kraken", "Kraken"),
    LAMIA("lamia", "Lamia"),
    LEMURE("lemure", "Lemure"),
    LICH("lich", "Lich"),
    LION("lion", "Lion"),
    LIZARD("lizard", "Lizard"),
    LIZARDFOLK("lizardfolk", "Lizardfolk"),
    MAGE("mage", "Mage"),
    MAGMA_MEPHIT("magma-mephit", "Magma Mephit"),
    MAGMIN("magmin", "Magmin"),
    MAMMOTH("mammoth", "Mammoth"),
    MANTICORE("manticore", "Manticore"),
    MARILITH("marilith", "Marilith"),
    MASTIFF("mastiff", "Mastiff"),
    MEDUSA("medusa", "Medusa"),
    MERFOLK("merfolk", "Merfolk"),
    MERROW("merrow", "Merrow"),
    MIMIC("mimic", "Mimic"),
    MINOTAUR("minotaur", "Minotaur"),
    MINOTAUR_SKELETON("minotaur-skeleton", "Minotaur Skeleton"),
    MULE("mule", "Mule"),
    MUMMY("mummy", "Mummy"),
    MUMMY_LORD("mummy-lord", "Mummy Lord"),
    NALFESHNEE("nalfeshnee", "Nalfeshnee"),
    NIGHT_HAG("night-hag", "Night Hag"),
    NIGHTMARE("nightmare", "Nightmare"),
    NOBLE("noble", "Noble"),
    OCHRE_JELLY("ochre-jelly", "Ochre Jelly"),
    OCTOPUS("octopus", "Octopus"),
    OGRE("ogre", "Ogre"),
    OGRE_ZOMBIE("ogre-zombie", "Ogre Zombie"),
    ONI("oni", "Oni"),
    ORC("orc", "Orc"),
    OTYUGH("otyugh", "Otyugh"),
    OWL("owl", "Owl"),
    OWLBEAR("owlbear", "Owlbear"),
    PANTHER("panther", "Panther"),
    PEGASUS("pegasus", "Pegasus"),
    PHASE_SPIDER("phase-spider", "Phase Spider"),
    PIT_FIEND("pit-fiend", "Pit Fiend"),
    PLANETAR("planetar", "Planetar"),
    PLESIOSAURUS("plesiosaurus", "Plesiosaurus"),
    POISONOUS_SNAKE("poisonous-snake", "Poisonous Snake"),
    POLAR_BEAR("polar-bear", "Polar Bear"),
    PONY("pony", "Pony"),
    PRIEST("priest", "Priest"),
    PSEUDODRAGON("pseudodragon", "Pseudodragon"),
    PURPLE_WORM("purple-worm", "Purple Worm"),
    QUASIT("quasit", "Quasit"),
    QUIPPER("quipper", "Quipper"),
    RAKSHASA("rakshasa", "Rakshasa"),
    RAT("rat", "Rat"),
    RAVEN("raven", "Raven"),
    RED_DRAGON_WYRMLING("red-dragon-wyrmling", "Red Dragon Wyrmling"),
    REEF_SHARK("reef-shark", "Reef Shark"),
    REMORHAZ("remorhaz", "Remorhaz"),
    RHINOCEROS("rhinoceros", "Rhinoceros"),
    RIDING_HORSE("riding-horse", "Riding Horse"),
    ROC("roc", "Roc"),
    ROPER("roper", "Roper"),
    RUG_OF_SMOTHERING("rug-of-smothering", "Rug of Smothering"),
    RUST_MONSTER("rust-monster", "Rust Monster"),
    SABER_TOOTHED_TIGER("saber-toothed-tiger", "Saber-Toothed Tiger"),
    SAHUAGIN("sahuagin", "Sahuagin"),
    SALAMANDER("salamander", "Salamander"),
    SATYR("satyr", "Satyr"),
    SCORPION("scorpion", "Scorpion"),
    SCOUT("scout", "Scout"),
    SEA_HAG("sea-hag", "Sea Hag"),
    SEA_HORSE("sea-horse", "Sea Horse"),
    SHADOW("shadow", "Shadow"),
    SHAMBLING_MOUND("shambling-mound", "Shambling Mound"),
    SHIELD_GUARDIAN("shield-guardian", "Shield Guardian"),
    SHRIEKER("shrieker", "Shrieker"),
    SILVER_DRAGON_WYRMLING("silver-dragon-wyrmling", "Silver Dragon Wyrmling"),
    SKELETON("skeleton", "Skeleton"),
    SOLAR("solar", "Solar"),
    SPECTER("specter", "Specter"),
    SPIDER("spider", "Spider"),
    SPIRIT_NAGA("spirit-naga", "Spirit Naga"),
    SPRITE("sprite", "Sprite"),
    SPY("spy", "Spy"),
    STEAM_MEPHIT("steam-mephit", "Steam Mephit"),
    STIRGE("stirge", "Stirge"),
    STONE_GIANT("stone-giant", "Stone Giant"),
    STONE_GOLEM("stone-golem", "Stone Golem"),
    STORM_GIANT("storm-giant", "Storm Giant"),
    SUCCUBUS_INCUBUS("succubus-incubus", "Succubus/Incubus"),
    SWARM_OF_BATS("swarm-of-bats", "Swarm of Bats"),
    SWARM_OF_BEETLES("swarm-of-beetles", "Swarm of Beetles"),
    SWARM_OF_CENTIPEDES("swarm-of-centipedes", "Swarm of Centipedes"),
    SWARM_OF_INSECTS("swarm-of-insects", "Swarm of Insects"),
    SWARM_OF_POISONOUS_SNAKES("swarm-of-poisonous-snakes", "Swarm of Poisonous Snakes"),
    SWARM_OF_QUIPPERS("swarm-of-quippers", "Swarm of Quippers"),
    SWARM_OF_RATS("swarm-of-rats", "Swarm of Rats"),
    SWARM_OF_RAVENS("swarm-of-ravens", "Swarm of Ravens"),
    SWARM_OF_SPIDERS("swarm-of-spiders", "Swarm of Spiders"),
    SWARM_OF_WASPS("swarm-of-wasps", "Swarm of Wasps"),
    TARRASQUE("tarrasque", "Tarrasque"),
    THUG("thug", "Thug"),
    TIGER("tiger", "Tiger"),
    TREANT("treant", "Treant"),
    TRIBAL_WARRIOR("tribal-warrior", "Tribal Warrior"),
    TRICERATOPS("triceratops", "Triceratops"),
    TROLL("troll", "Troll"),
    TYRANNOSAURUS_REX("tyrannosaurus-rex", "Tyrannosaurus Rex"),
    UNICORN("unicorn", "Unicorn"),
    VAMPIRE_SPAWN("vampire-spawn", "Vampire Spawn"),
    VAMPIRE_BAT("vampire-bat", "Vampire, Bat Form"),
    VAMPIRE_MIST("vampire-mist", "Vampire, Mist Form"),
    VAMPIRE_VAMPIRE("vampire-vampire", "Vampire, Vampire Form"),
    VETERAN("veteran", "Veteran"),
    VIOLET_FUNGUS("violet-fungus", "Violet Fungus"),
    VROCK("vrock", "Vrock"),
    VULTURE("vulture", "Vulture"),
    WARHORSE("warhorse", "Warhorse"),
    WARHORSE_SKELETON("warhorse-skeleton", "Warhorse Skeleton"),
    WATER_ELEMENTAL("water-elemental", "Water Elemental"),
    WEASEL("weasel", "Weasel"),
    WEREBEAR_BEAR("werebear-bear", "Werebear, Bear Form"),
    WEREBEAR_HUMAN("werebear-human", "Werebear, Human Form"),
    WEREBEAR_HYBRID("werebear-hybrid", "Werebear, Hybrid Form"),
    WEREBOAR_BOAR("wereboar-boar", "Wereboar, Boar Form"),
    WEREBOAR_HUMAN("wereboar-human", "Wereboar, Human Form"),
    WEREBOAR_HYBRID("wereboar-hybrid", "Wereboar, Hybrid Form"),
    WERERAT_HUMAN("wererat-human", "Wererat, Human Form"),
    WERERAT_HYBRID("wererat-hybrid", "Wererat, Hybrid Form"),
    WERERAT_RAT("wererat-rat", "Wererat, Rat Form"),
    WERETIGER_HUMAN("weretiger-human", "Weretiger, Human Form"),
    WERETIGER_HYBRID("weretiger-hybrid", "Weretiger, Hybrid Form"),
    WERETIGER_TIGER("weretiger-tiger", "Weretiger, Tiger Form"),
    WEREWOLF_HUMAN("werewolf-human", "Werewolf, Human Form"),
    WEREWOLF_HYBRID("werewolf-hybrid", "Werewolf, Hybrid Form"),
    WEREWOLF_WOLF("werewolf-wolf", "Werewolf, Wolf Form"),
    WHITE_DRAGON_WYRMLING("white-dragon-wyrmling", "White Dragon Wyrmling"),
    WIGHT("wight", "Wight"),
    WILL_O_WISP("will-o-wisp", "Will-o'-Wisp"),
    WINTER_WOLF("winter-wolf", "Winter Wolf"),
    WOLF("wolf", "Wolf"),
    WORG("worg", "Worg"),
    WRAITH("wraith", "Wraith"),
    WYVERN("wyvern", "Wyvern"),
    XORN("xorn", "Xorn"),
    YOUNG_BLACK_DRAGON("young-black-dragon", "Young Black Dragon"),
    YOUNG_BLUE_DRAGON("young-blue-dragon", "Young Blue Dragon"),
    YOUNG_BRASS_DRAGON("young-brass-dragon", "Young Brass Dragon"),
    YOUNG_BRONZE_DRAGON("young-bronze-dragon", "Young Bronze Dragon"),
    YOUNG_COPPER_DRAGON("young-copper-dragon", "Young Copper Dragon"),
    YOUNG_GOLD_DRAGON("young-gold-dragon", "Young Gold Dragon"),
    YOUNG_GREEN_DRAGON("young-green-dragon", "Young Green Dragon"),
    YOUNG_RED_DRAGON("young-red-dragon", "Young Red Dragon"),
    YOUNG_SILVER_DRAGON("young-silver-dragon", "Young Silver Dragon"),
    YOUNG_WHITE_DRAGON("young-white-dragon", "Young White Dragon"),
    ZOMBIE("zombie", "Zombie");

    private final String index;
    private final String name;

    public static MonsterNameEnum fromIndex(String index) {
        for (MonsterNameEnum name : MonsterNameEnum.values()) {
            if (name.index.equalsIgnoreCase(index)) {
                return name;
            }
        }
        throw new IllegalArgumentException("No enum constant for index: " + index);
    }

    @JsonCreator
    public static MonsterNameEnum fromString(String value) {
        if (value == null) {
            return null;
        }
        String normalized = value.trim().toLowerCase();

        return Stream.of(MonsterNameEnum.values())
                .filter(g -> g.name().toLowerCase().equals(normalized) ||
                        g.getIndex().toLowerCase().equals(normalized) ||
                        g.getName().toLowerCase().equals(normalized))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Nome não reconhecido: " + value));
    }
}
