package com.raphaowl.dnd.enums;

import java.util.Map;

import com.raphaowl.dnd.dtos.Spell;

import lombok.Getter;

@Getter
public enum SpellEnum {
    ACID_SPLASH("Acid Splash", 0, MagicSchool.CONJURATION, null, null),
    AID("Aid", 2, MagicSchool.ABJURATION, null, null),
    ALARM("Alarm", 1, MagicSchool.ABJURATION, null, null),
    ALTER_SELF("Alter Self", 2, MagicSchool.TRANSMUTATION, null, null),
    ANIMAL_FRIENDSHIP("Animal Friendship", 1, MagicSchool.ENCHANTMENT, null, null),
    ANIMAL_MESSENGER("Animal Messenger", 2, MagicSchool.ENCHANTMENT, null, null),
    ANIMAL_SHAPES("Animal Shapes", 8, MagicSchool.TRANSMUTATION, null, null),
    ANIMATE_DEAD("Animate Dead", 3, MagicSchool.NECROMANCY, null, null),
    ANIMATE_OBJECTS("Animate Objects", 5, MagicSchool.TRANSMUTATION, null, null),
    ANTILIFE_SHELL("Antilife Shell", 5, MagicSchool.ABJURATION, null, null),
    ANTIMAGIC_FIELD("Antimagic Field", 8, MagicSchool.ABJURATION, null, null),
    ANTIPATHY_SYMPATHY("Antipathy/Sympathy", 8, MagicSchool.ENCHANTMENT, null, null),
    ARCANE_EYE("Arcane Eye", 4, MagicSchool.DIVINATION, null, null),
    ARCANE_LOCK("Arcane Lock", 2, MagicSchool.ABJURATION, null, null),
    ASTRAL_PROJECTION("Astral Projection", 9, MagicSchool.NECROMANCY, null, null),
    AUGURY("Augury", 2, MagicSchool.DIVINATION, null, null),
    AWAKEN("Awaken", 5, MagicSchool.TRANSMUTATION, null, null),
    BANE("Bane", 1, MagicSchool.ENCHANTMENT, null, null),
    BANISHMENT("Banishment", 4, MagicSchool.ABJURATION, null, null),
    BARKSKIN("Barkskin", 2, MagicSchool.TRANSMUTATION, null, null),
    BEACON_OF_HOPE("Beacon of Hope", 3, MagicSchool.ABJURATION, null, null),
    BESTOW_CURSE("Bestow Curse", 3, MagicSchool.NECROMANCY, null, null),
    BLADE_BARRIER("Blade Barrier", 6, MagicSchool.EVOCATION, DamageEnum.SLASHING, Map.of(6, "6d10")),
    BLESS("Bless", 1, MagicSchool.ENCHANTMENT, null, null),
    BLIGHT("Blight", 4, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(4, "8d8", 5, "9d8", 6, "10d8", 7, "11d8", 8, "12d8", 9, "13d8")),
    BLINDNESS_DEAFNESS("Blindness/Deafness", 2, MagicSchool.NECROMANCY, null, null),
    BLINK("Blink", 3, MagicSchool.TRANSMUTATION, null, null),
    BLUR("Blur", 2, MagicSchool.ILLUSION, null, null),
    BRANDING_SMITE("Branding Smite", 2, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(2, "2d6", 3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6")),
    BURNING_HANDS("Burning Hands", 1, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(1, "3d6", 2, "4d6", 3, "5d6", 4, "6d6", 5, "7d6", 6, "8d6", 7, "9d6", 8, "10d6", 9, "11d6")),
    CALL_LIGHTNING("Call Lightning", 3, MagicSchool.CONJURATION, DamageEnum.LIGHTNING, Map.of(3, "3d10", 4, "4d10", 5, "5d10", 6, "6d10", 7, "7d10", 8, "8d10", 9, "9d10")),
    CALM_EMOTIONS("Calm Emotions", 2, MagicSchool.ENCHANTMENT, null, null),
    CHAIN_LIGHTNING("Chain Lightning", 6, MagicSchool.EVOCATION, DamageEnum.LIGHTNING, Map.of(6, "10d8")),
    CHARM_PERSON("Charm Person", 1, MagicSchool.ENCHANTMENT, null, null),
    CHILL_TOUCH("Chill Touch", 0, MagicSchool.NECROMANCY, null, null),
    CIRCLE_OF_DEATH("Circle of Death", 6, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(6, "8d6", 7, "10d6", 8, "12d6", 9, "14d6")),
    CLAIRVOYANCE("Clairvoyance", 3, MagicSchool.DIVINATION, null, null),
    CLONE("Clone", 8, MagicSchool.NECROMANCY, null, null),
    CLOUDKILL("Cloudkill", 5, MagicSchool.CONJURATION, DamageEnum.POISON, Map.of(5, "5d8", 6, "6d8", 7, "7d8", 8, "8d8", 9, "9d8")),
    COLOR_SPRAY("Color Spray", 1, MagicSchool.ILLUSION, null, null),
    COMMAND("Command", 1, MagicSchool.ENCHANTMENT, null, null),
    COMMUNE("Commune", 5, MagicSchool.DIVINATION, null, null),
    COMMUNE_WITH_NATURE("Commune With Nature", 5, MagicSchool.DIVINATION, null, null),
    COMPREHEND_LANGUAGES("Comprehend Languages", 1, MagicSchool.DIVINATION, null, null),
    COMPULSION("Compulsion", 4, MagicSchool.ENCHANTMENT, null, null),
    CONE_OF_COLD("Cone of Cold", 5, MagicSchool.EVOCATION, DamageEnum.COLD, Map.of(5, "8d8", 6, "9d8", 7, "10d8", 8, "11d8", 9, "12d8")),
    CONFUSION("Confusion", 4, MagicSchool.ENCHANTMENT, null, null),
    CONJURE_ANIMALS("Conjure Animals", 3, MagicSchool.CONJURATION, null, null),
    CONJURE_CELESTIAL("Conjure Celestial", 7, MagicSchool.CONJURATION, null, null),
    CONJURE_ELEMENTAL("Conjure Elemental", 5, MagicSchool.CONJURATION, null, null),
    CONJURE_FEY("Conjure Fey", 6, MagicSchool.CONJURATION, null, null),
    CONJURE_MINOR_ELEMENTALS("Conjure Minor Elementals", 4, MagicSchool.CONJURATION, null, null),
    CONJURE_WOODLAND_BEINGS("Conjure Woodland Beings", 4, MagicSchool.CONJURATION, null, null),
    CONTACT_OTHER_PLANE("Contact Other Plane", 5, MagicSchool.DIVINATION, null, null),
    CONTAGION("Contagion", 5, MagicSchool.NECROMANCY, null, null),
    CONTINGENCY("Contingency", 6, MagicSchool.EVOCATION, null, null),
    CONTINUAL_FLAME("Continual Flame", 2, MagicSchool.EVOCATION, null, null),
    CONTROL_WATER("Control Water", 4, MagicSchool.TRANSMUTATION, DamageEnum.BLUDGEONING, Map.of(4, "2d8")),
    CONTROL_WEATHER("Control Weather", 8, MagicSchool.TRANSMUTATION, null, null),
    COUNTERSPELL("Counterspell", 3, MagicSchool.ABJURATION, null, null),
    CREATE_FOOD_AND_WATER("Create Food and Water", 3, MagicSchool.CONJURATION, null, null),
    CREATE_UNDEAD("Create Undead", 6, MagicSchool.NECROMANCY, null, null),
    CREATE_OR_DESTROY_WATER("Create or Destroy Water", 1, MagicSchool.TRANSMUTATION, null, null),
    CREATION("Creation", 5, MagicSchool.ILLUSION, null, null),
    CURE_WOUNDS("Cure Wounds", 1, MagicSchool.EVOCATION, null, null),
    DANCING_LIGHTS("Dancing Lights", 0, MagicSchool.EVOCATION, null, null),
    DARKNESS("Darkness", 2, MagicSchool.EVOCATION, null, null),
    DARKVISION("Darkvision", 2, MagicSchool.TRANSMUTATION, null, null),
    DAYLIGHT("Daylight", 3, MagicSchool.EVOCATION, null, null),
    DEATH_WARD("Death Ward", 4, MagicSchool.ABJURATION, null, null),
    DELAYED_BLAST_FIREBALL("Delayed Blast Fireball", 7, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(7, "12d6", 8, "13d6", 9, "14d6")),
    DEMIPLANE("Demiplane", 8, MagicSchool.CONJURATION, null, null),
    DETECT_EVIL_AND_GOOD("Detect Evil and Good", 1, MagicSchool.DIVINATION, null, null),
    DETECT_MAGIC("Detect Magic", 1, MagicSchool.DIVINATION, null, null),
    DETECT_POISON_AND_DISEASE("Detect Poison and Disease", 1, MagicSchool.DIVINATION, null, null),
    DETECT_THOUGHTS("Detect Thoughts", 2, MagicSchool.DIVINATION, null, null),
    DIMENSION_DOOR("Dimension Door", 4, MagicSchool.CONJURATION, DamageEnum.FORCE, Map.of(4, "4d6")),
    DISGUISE_SELF("Disguise Self", 1, MagicSchool.ILLUSION, null, null),
    DISINTEGRATE("Disintegrate", 6, MagicSchool.TRANSMUTATION, DamageEnum.FORCE, Map.of(6, "10d6 + 40")),
    DISPEL_EVIL_AND_GOOD("Dispel Evil and Good", 5, MagicSchool.ABJURATION, null, null),
    DISPEL_MAGIC("Dispel Magic", 3, MagicSchool.ABJURATION, null, null),
    DIVINATION("Divination", 4, MagicSchool.DIVINATION, null, null),
    DIVINE_FAVOR("Divine Favor", 1, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(1, "1d4")),
    DIVINE_WORD("Divine Word", 7, MagicSchool.EVOCATION, null, null),
    DOMINATE_BEAST("Dominate Beast", 4, MagicSchool.ENCHANTMENT, null, null),
    DOMINATE_MONSTER("Dominate Monster", 8, MagicSchool.ENCHANTMENT, null, null),
    DOMINATE_PERSON("Dominate Person", 5, MagicSchool.ENCHANTMENT, null, null),
    DREAM("Dream", 5, MagicSchool.ILLUSION, DamageEnum.PSYCHIC, Map.of(5, "3d6")),
    DRUIDCRAFT("Druidcraft", 0, MagicSchool.TRANSMUTATION, null, null),
    EARTHQUAKE("Earthquake", 8, MagicSchool.EVOCATION, null, null),
    ELDRITCH_BLAST("Eldritch Blast", 0, MagicSchool.EVOCATION, null, null),
    ENHANCE_ABILITY("Enhance Ability", 2, MagicSchool.TRANSMUTATION, null, null),
    ENLARGE_REDUCE("Enlarge/Reduce", 2, MagicSchool.TRANSMUTATION, null, null),
    ENTANGLE("Entangle", 1, MagicSchool.CONJURATION, null, null),
    ENTHRALL("Enthrall", 2, MagicSchool.ENCHANTMENT, null, null),
    ETHEREALNESS("Etherealness", 7, MagicSchool.TRANSMUTATION, null, null),
    EXPEDITIOUS_RETREAT("Expeditious Retreat", 1, MagicSchool.TRANSMUTATION, null, null),
    EYEBITE("Eyebite", 6, MagicSchool.NECROMANCY, null, null),
    FABRICATE("Fabricate", 4, MagicSchool.TRANSMUTATION, null, null),
    FAERIE_FIRE("Faerie Fire", 1, MagicSchool.EVOCATION, null, null),
    FAITHFUL_HOUND("Faithful Hound", 4, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(4, "4d8")),
    FALSE_LIFE("False Life", 1, MagicSchool.NECROMANCY, null, null),
    FEAR("Fear", 3, MagicSchool.ILLUSION, null, null),
    FEATHER_FALL("Feather Fall", 1, MagicSchool.TRANSMUTATION, null, null),
    FEEBLEMIND("Feeblemind", 8, MagicSchool.ENCHANTMENT, DamageEnum.PSYCHIC, Map.of(8, "4d6")),
    FIND_FAMILIAR("Find Familiar", 1, MagicSchool.CONJURATION, null, null),
    FIND_STEED("Find Steed", 2, MagicSchool.CONJURATION, null, null),
    FIND_TRAPS("Find Traps", 2, MagicSchool.DIVINATION, null, null),
    FIND_THE_PATH("Find the Path", 6, MagicSchool.DIVINATION, null, null),
    FINGER_OF_DEATH("Finger of Death", 7, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(7, "7d8 + 30")),
    FIRE_BOLT("Fire Bolt", 0, MagicSchool.EVOCATION, null, null),
    FIRE_SHIELD("Fire Shield", 4, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(4, "2d8")),
    FIRE_STORM("Fire Storm", 7, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(7, "7d10")),
    FIREBALL("Fireball", 3, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(3, "8d6", 4, "9d6", 5, "10d6", 6, "11d6", 7, "12d6", 8, "13d6", 9, "14d6")),
    FLAME_BLADE("Flame Blade", 2, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(2, "3d6", 4, "4d6", 6, "5d6", 8, "6d6")),
    FLAME_STRIKE("Flame Strike", 5, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(5, "4d6 + 4d6", 6, "4d6 + 5d6", 7, "4d6 + 6d6", 8, "4d6 + 7d6", 9, "4d6 + 8d6")),
    FLAMING_SPHERE("Flaming Sphere", 2, MagicSchool.CONJURATION, DamageEnum.FIRE, Map.of(2, "2d6", 3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6")),
    FLESH_TO_STONE("Flesh to Stone", 6, MagicSchool.TRANSMUTATION, null, null),
    FLY("Fly", 3, MagicSchool.TRANSMUTATION, null, null),
    FOG_CLOUD("Fog Cloud", 1, MagicSchool.CONJURATION, null, null),
    FORBIDDANCE("Forbiddance", 6, MagicSchool.ABJURATION, null, null),
    FORCECAGE("Forcecage", 7, MagicSchool.EVOCATION, null, null),
    FORESIGHT("Foresight", 9, MagicSchool.DIVINATION, null, null),
    FREEDOM_OF_MOVEMENT("Freedom of Movement", 4, MagicSchool.ABJURATION, null, null),
    FREEZING_SPHERE("Freezing Sphere", 6, MagicSchool.EVOCATION, DamageEnum.COLD, Map.of(6, "10d6")),
    GASEOUS_FORM("Gaseous Form", 3, MagicSchool.TRANSMUTATION, null, null),
    GATE("Gate", 9, MagicSchool.CONJURATION, null, null),
    GEAS("Geas", 5, MagicSchool.ENCHANTMENT, null, null),
    GENTLE_REPOSE("Gentle Repose", 2, MagicSchool.NECROMANCY, null, null),
    GIANT_INSECT("Giant Insect", 4, MagicSchool.TRANSMUTATION, null, null),
    GLIBNESS("Glibness", 8, MagicSchool.TRANSMUTATION, null, null),
    GLOBE_OF_INVULNERABILITY("Globe of Invulnerability", 6, MagicSchool.ABJURATION, null, null),
    GLYPH_OF_WARDING("Glyph of Warding", 3, MagicSchool.ABJURATION, null, null),
    GOODBERRY("Goodberry", 1, MagicSchool.TRANSMUTATION, null, null),
    GREASE("Grease", 1, MagicSchool.CONJURATION, null, null),
    GREATER_INVISIBILITY("Greater Invisibility", 4, MagicSchool.ILLUSION, null, null),
    GREATER_RESTORATION("Greater Restoration", 5, MagicSchool.ABJURATION, null, null),
    GUARDIAN_OF_FAITH("Guardian of Faith", 4, MagicSchool.CONJURATION, DamageEnum.RADIANT, Map.of(4, "20")),
    GUARDS_AND_WARDS("Guards and Wards", 6, MagicSchool.ABJURATION, null, null),
    GUIDANCE("Guidance", 0, MagicSchool.DIVINATION, null, null),
    GUIDING_BOLT("Guiding Bolt", 1, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(1, "4d6", 2, "5d6", 3, "6d6", 4, "7d6", 5, "8d6", 6, "9d6", 7, "10d6", 8, "11d6", 9, "12d6")),
    GUST_OF_WIND("Gust of Wind", 2, MagicSchool.EVOCATION, null, null),
    HALLOW("Hallow", 5, MagicSchool.EVOCATION, null, null),
    HALLUCINATORY_TERRAIN("Hallucinatory Terrain", 4, MagicSchool.ILLUSION, null, null),
    HARM("Harm", 6, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(6, "14d6")),
    HASTE("Haste", 3, MagicSchool.TRANSMUTATION, null, null),
    HEAL("Heal", 6, MagicSchool.EVOCATION, null, null),
    HEALING_WORD("Healing Word", 1, MagicSchool.EVOCATION, null, null),
    HEAT_METAL("Heat Metal", 2, MagicSchool.TRANSMUTATION, DamageEnum.FIRE, Map.of(2, "2d8", 3, "3d8", 4, "4d8", 5, "5d8", 6, "6d8", 7, "7d8", 8, "8d8", 9, "9d8")),
    HELLISH_REBUKE("Hellish Rebuke", 1, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(1, "2d10", 2, "3d10", 3, "4d10", 4, "5d10", 5, "6d10", 6, "7d10", 7, "8d10", 8, "9d10", 9, "10d10")),
    HEROES_FEAST("Heroes' Feast", 6, MagicSchool.CONJURATION, null, null),
    HEROISM("Heroism", 1, MagicSchool.ENCHANTMENT, null, null),
    HOLD_MONSTER("Hold Monster", 5, MagicSchool.ENCHANTMENT, null, null),
    HOLD_PERSON("Hold Person", 2, MagicSchool.ENCHANTMENT, null, null),
    HOLY_AURA("Holy Aura", 8, MagicSchool.ABJURATION, null, null),
    HUNTERS_MARK("Hunter's Mark", 1, MagicSchool.DIVINATION, null, null),
    HYPNOTIC_PATTERN("Hypnotic Pattern", 3, MagicSchool.ILLUSION, null, null),
    ICE_STORM("Ice Storm", 4, MagicSchool.EVOCATION, DamageEnum.BLUDGEONING, Map.of(4, "2d8 + 4d6", 5, "3d8 + 4d6", 6, "4d8 + 4d6", 7, "5d8 + 4d6", 8, "6d8 + 4d6", 9, "7d8 + 4d6")),
    IDENTIFY("Identify", 1, MagicSchool.DIVINATION, null, null),
    ILLUSORY_SCRIPT("Illusory Script", 1, MagicSchool.ILLUSION, null, null),
    IMPRISONMENT("Imprisonment", 9, MagicSchool.ABJURATION, null, null),
    INCENDIARY_CLOUD("Incendiary Cloud", 8, MagicSchool.CONJURATION, DamageEnum.FIRE, Map.of(8, "10d8")),
    INFLICT_WOUNDS("Inflict Wounds", 1, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(1, "3d10", 2, "4d10", 3, "5d10", 4, "6d10", 5, "7d10", 6, "8d10", 7, "9d10", 8, "10d10", 9, "11d10")),
    INSECT_PLAGUE("Insect Plague", 5, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(5, "4d10", 6, "5d10", 7, "6d10", 8, "7d10", 9, "8d10")),
    INSTANT_SUMMONS("Instant Summons", 6, MagicSchool.CONJURATION, null, null),
    INVISIBILITY("Invisibility", 2, MagicSchool.ILLUSION, null, null),
    JUMP("Jump", 1, MagicSchool.TRANSMUTATION, null, null),
    KNOCK("Knock", 2, MagicSchool.TRANSMUTATION, null, null),
    LEGEND_LORE("Legend Lore", 5, MagicSchool.DIVINATION, null, null),
    LESSER_RESTORATION("Lesser Restoration", 2, MagicSchool.ABJURATION, null, null),
    LEVITATE("Levitate", 2, MagicSchool.TRANSMUTATION, null, null),
    LIGHT("Light", 0, MagicSchool.EVOCATION, null, null),
    LIGHTNING_BOLT("Lightning Bolt", 3, MagicSchool.EVOCATION, DamageEnum.LIGHTNING, Map.of(3, "8d6", 4, "9d6", 5, "10d6", 6, "11d6", 7, "12d6", 8, "13d6", 9, "14d6")),
    LOCATE_ANIMALS_OR_PLANTS("Locate Animals or Plants", 2, MagicSchool.DIVINATION, null, null),
    LOCATE_CREATURE("Locate Creature", 4, MagicSchool.DIVINATION, null, null),
    LOCATE_OBJECT("Locate Object", 2, MagicSchool.DIVINATION, null, null),
    LONGSTRIDER("Longstrider", 1, MagicSchool.TRANSMUTATION, null, null),
    MAGE_ARMOR("Mage Armor", 1, MagicSchool.ABJURATION, null, null),
    MAGE_HAND("Mage Hand", 0, MagicSchool.CONJURATION, null, null),
    MAGIC_CIRCLE("Magic Circle", 3, MagicSchool.ABJURATION, null, null),
    MAGIC_JAR("Magic Jar", 6, MagicSchool.NECROMANCY, null, null),
    MAGIC_MISSILE("Magic Missile", 1, MagicSchool.EVOCATION, DamageEnum.FORCE, Map.of(1, "1d4 + 1", 2, "1d4 + 1", 3, "1d4 + 1", 4, "1d4 + 1", 5, "1d4 + 1", 6, "1d4 + 1", 7, "1d4 + 1", 8, "1d4 + 1", 9, "1d4 + 1")),
    MAGIC_MOUTH("Magic Mouth", 2, MagicSchool.ILLUSION, null, null),
    MAGIC_WEAPON("Magic Weapon", 2, MagicSchool.TRANSMUTATION, null, null),
    MAGNIFICENT_MANSION("Magnificent Mansion", 7, MagicSchool.CONJURATION, null, null),
    MAJOR_IMAGE("Major Image", 3, MagicSchool.ILLUSION, null, null),
    MASS_CURE_WOUNDS("Mass Cure Wounds", 5, MagicSchool.CONJURATION, null, null),
    MASS_HEAL("Mass Heal", 9, MagicSchool.CONJURATION, null, null),
    MASS_HEALING_WORD("Mass Healing Word", 3, MagicSchool.EVOCATION, null, null),
    MASS_SUGGESTION("Mass Suggestion", 6, MagicSchool.ENCHANTMENT, null, null),
    MAZE("Maze", 8, MagicSchool.CONJURATION, null, null),
    MELD_INTO_STONE("Meld Into Stone", 3, MagicSchool.TRANSMUTATION, null, null),
    MENDING("Mending", 0, MagicSchool.TRANSMUTATION, null, null),
    MESSAGE("Message", 0, MagicSchool.TRANSMUTATION, null, null),
    METEOR_SWARM("Meteor Swarm", 9, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(9, "20d6 + 20d6")),
    MIND_BLANK("Mind Blank", 8, MagicSchool.ABJURATION, null, null),
    MINOR_ILLUSION("Minor Illusion", 0, MagicSchool.ILLUSION, null, null),
    MIRAGE_ARCANE("Mirage Arcane", 7, MagicSchool.ILLUSION, null, null),
    MIRROR_IMAGE("Mirror Image", 2, MagicSchool.ILLUSION, null, null),
    MISLEAD("Mislead", 5, MagicSchool.ILLUSION, null, null),
    MISTY_STEP("Misty Step", 2, MagicSchool.CONJURATION, null, null),
    MODIFY_MEMORY("Modify Memory", 5, MagicSchool.ENCHANTMENT, null, null),
    MOONBEAM("Moonbeam", 2, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(2, "2d10", 3, "3d10", 4, "4d10", 5, "5d10", 6, "6d10", 7, "7d10", 8, "8d10", 9, "9d10")),
    MOVE_EARTH("Move Earth", 6, MagicSchool.TRANSMUTATION, null, null),
    NONDETECTION("Nondetection", 3, MagicSchool.ABJURATION, null, null),
    PASS_WITHOUT_TRACE("Pass Without Trace", 2, MagicSchool.ABJURATION, null, null),
    PASSWALL("Passwall", 5, MagicSchool.TRANSMUTATION, null, null),
    PHANTASMAL_KILLER("Phantasmal Killer", 4, MagicSchool.ILLUSION, DamageEnum.PSYCHIC, Map.of(4, "4d10")),
    PHANTOM_STEED("Phantom Steed", 3, MagicSchool.ILLUSION, null, null),
    PLANAR_ALLY("Planar Ally", 6, MagicSchool.CONJURATION, null, null),
    PLANAR_BINDING("Planar Binding", 5, MagicSchool.ABJURATION, null, null),
    PLANE_SHIFT("Plane Shift", 7, MagicSchool.CONJURATION, null, null),
    PLANT_GROWTH("Plant Growth", 3, MagicSchool.TRANSMUTATION, null, null),
    POISON_SPRAY("Poison Spray", 0, MagicSchool.CONJURATION, null, null),
    POLYMORPH("Polymorph", 4, MagicSchool.TRANSMUTATION, null, null),
    POWER_WORD_KILL("Power Word Kill", 9, MagicSchool.ENCHANTMENT, null, null),
    POWER_WORD_STUN("Power Word Stun", 8, MagicSchool.ENCHANTMENT, null, null),
    PRAYER_OF_HEALING("Prayer of Healing", 2, MagicSchool.EVOCATION, null, null),
    PRESTIDIGITATION("Prestidigitation", 0, MagicSchool.TRANSMUTATION, null, null),
    PRISMATIC_SPRAY("Prismatic Spray", 7, MagicSchool.EVOCATION, null, Map.of(7, "10d6")),
    PRISMATIC_WALL("Prismatic Wall", 9, MagicSchool.ABJURATION, null, null),
    PRIVATE_SANCTUM("Private Sanctum", 4, MagicSchool.ABJURATION, null, null),
    PRODUCE_FLAME("Produce Flame", 0, MagicSchool.CONJURATION, null, null),
    PROGRAMMED_ILLUSION("Programmed Illusion", 6, MagicSchool.ILLUSION, null, null),
    PROJECT_IMAGE("Project Image", 7, MagicSchool.ILLUSION, null, null),
    PROTECTION_FROM_ENERGY("Protection From Energy", 3, MagicSchool.ABJURATION, null, null),
    PROTECTION_FROM_EVIL_AND_GOOD("Protection from Evil and Good", 1, MagicSchool.ABJURATION, null, null),
    PROTECTION_FROM_POISON("Protection from Poison", 2, MagicSchool.ABJURATION, null, null),
    PURIFY_FOOD_AND_DRINK("Purify Food and Drink", 1, MagicSchool.TRANSMUTATION, null, null),
    RAISE_DEAD("Raise Dead", 5, MagicSchool.NECROMANCY, null, null),
    RAY_OF_ENFEEBLEMENT("Ray of Enfeeblement", 2, MagicSchool.NECROMANCY, null, null),
    RAY_OF_FROST("Ray of Frost", 0, MagicSchool.EVOCATION, null, null),
    REGENERATE("Regenerate", 7, MagicSchool.TRANSMUTATION, null, null),
    REINCARNATE("Reincarnate", 5, MagicSchool.TRANSMUTATION, null, null),
    REMOVE_CURSE("Remove Curse", 3, MagicSchool.ABJURATION, null, null),
    RESILIENT_SPHERE("Resilient Sphere", 4, MagicSchool.EVOCATION, null, null),
    RESISTANCE("Resistance", 0, MagicSchool.ABJURATION, null, null),
    RESURRECTION("Resurrection", 7, MagicSchool.NECROMANCY, null, null),
    REVERSE_GRAVITY("Reverse Gravity", 7, MagicSchool.TRANSMUTATION, null, null),
    REVIVIFY("Revivify", 3, MagicSchool.CONJURATION, null, null),
    ROPE_TRICK("Rope Trick", 2, MagicSchool.TRANSMUTATION, null, null),
    SACRED_FLAME("Sacred Flame", 0, MagicSchool.EVOCATION, null, null),
    SANCTUARY("Sanctuary", 1, MagicSchool.ABJURATION, null, null),
    SCORCHING_RAY("Scorching Ray", 2, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(2, "2d6")),
    SCRYING("Scrying", 5, MagicSchool.DIVINATION, null, null),
    SECRET_CHEST("Secret Chest", 4, MagicSchool.CONJURATION, null, null),
    SEE_INVISIBILITY("See Invisibility", 2, MagicSchool.DIVINATION, null, null),
    SEEMING("Seeming", 5, MagicSchool.ILLUSION, null, null),
    SENDING("Sending", 3, MagicSchool.EVOCATION, null, null),
    SEQUESTER("Sequester", 7, MagicSchool.TRANSMUTATION, null, null),
    SHAPECHANGE("Shapechange", 9, MagicSchool.TRANSMUTATION, null, null),
    SHATTER("Shatter", 2, MagicSchool.EVOCATION, DamageEnum.THUNDER, Map.of(2, "3d8", 3, "4d8", 4, "5d8", 5, "6d8", 6, "7d8", 7, "8d8", 8, "9d8", 9, "10d8")),
    SHIELD("Shield", 1, MagicSchool.ABJURATION, null, null),
    SHIELD_OF_FAITH("Shield of Faith", 1, MagicSchool.ABJURATION, null, null),
    SHILLELAGH("Shillelagh", 0, MagicSchool.TRANSMUTATION, null, null),
    SHOCKING_GRASP("Shocking Grasp", 0, MagicSchool.EVOCATION, null, null),
    SILENCE("Silence", 2, MagicSchool.ILLUSION, null, null),
    SILENT_IMAGE("Silent Image", 1, MagicSchool.ILLUSION, null, null),
    SIMULACRUM("Simulacrum", 7, MagicSchool.ILLUSION, null, null),
    SLEEP("Sleep", 1, MagicSchool.ENCHANTMENT, null, Map.of(1, "5d8")),
    SLEET_STORM("Sleet Storm", 3, MagicSchool.CONJURATION, null, null),
    SLOW("Slow", 3, MagicSchool.TRANSMUTATION, null, null),
    SPARE_THE_DYING("Spare the Dying", 0, MagicSchool.NECROMANCY, null, null),
    SPEAK_WITH_ANIMALS("Speak with Animals", 1, MagicSchool.DIVINATION, null, null),
    SPEAK_WITH_DEAD("Speak with Dead", 3, MagicSchool.NECROMANCY, null, null),
    SPEAK_WITH_PLANTS("Speak with Plants", 3, MagicSchool.TRANSMUTATION, null, null),
    SPIDER_CLIMB("Spider Climb", 2, MagicSchool.TRANSMUTATION, null, null),
    SPIKE_GROWTH("Spike Growth", 2, MagicSchool.TRANSMUTATION, null, null),
    SPIRIT_GUARDIANS("Spirit Guardians", 3, MagicSchool.CONJURATION, null, null),
    SPIRITUAL_WEAPON("Spiritual Weapon", 2, MagicSchool.EVOCATION, DamageEnum.FORCE, Map.of(2, "1d8 + MOD", 3, "1d8 + MOD", 4, "2d8 + MOD", 5, "2d8 + MOD", 6, "3d8 + MOD", 7, "3d8 + MOD", 8, "4d8 + MOD", 9, "4d8 + MOD")),
    STINKING_CLOUD("Stinking Cloud", 3, MagicSchool.CONJURATION, null, null),
    STONE_SHAPE("Stone Shape", 4, MagicSchool.TRANSMUTATION, null, null),
    STONESKIN("Stoneskin", 4, MagicSchool.ABJURATION, null, null),
    STORM_OF_VENGEANCE("Storm of Vengeance", 9, MagicSchool.CONJURATION, DamageEnum.THUNDER, Map.of(9, "2d6")),
    SUGGESTION("Suggestion", 2, MagicSchool.ENCHANTMENT, null, null),
    SUNBEAM("Sunbeam", 6, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(6, "6d8")),
    SUNBURST("Sunburst", 8, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(8, "12d6")),
    SYMBOL("Symbol", 7, MagicSchool.ABJURATION, null, null),
    TELEKINESIS("Telekinesis", 5, MagicSchool.TRANSMUTATION, null, null),
    TELEPATHIC_BOND("Telepathic Bond", 5, MagicSchool.DIVINATION, null, null),
    TELEPORT("Teleport", 7, MagicSchool.CONJURATION, null, null),
    TELEPORTATION_CIRCLE("Teleportation Circle", 5, MagicSchool.CONJURATION, null, null),
    THAUMATURGY("Thaumaturgy", 0, MagicSchool.TRANSMUTATION, null, null),
    THUNDERWAVE("Thunderwave", 1, MagicSchool.EVOCATION, DamageEnum.THUNDER, Map.of(1, "2d8", 2, "3d8", 3, "4d8", 4, "5d8", 5, "6d8", 6, "7d8", 7, "8d8", 8, "9d8", 9, "10d8")),
    TIME_STOP("Time Stop", 9, MagicSchool.TRANSMUTATION, null, null),
    TINY_HUT("Tiny Hut", 3, MagicSchool.EVOCATION, null, null),
    TONGUES("Tongues", 3, MagicSchool.DIVINATION, null, null),
    TRANSPORT_VIA_PLANTS("Transport via Plants", 6, MagicSchool.CONJURATION, null, null),
    TREE_STRIDE("Tree Stride", 5, MagicSchool.CONJURATION, null, null),
    TRUE_POLYMORPH("True Polymorph", 9, MagicSchool.TRANSMUTATION, null, null),
    TRUE_RESURRECTION("True Resurrection", 9, MagicSchool.NECROMANCY, null, null),
    TRUE_SEEING("True Seeing", 6, MagicSchool.DIVINATION, null, null),
    TRUE_STRIKE("True Strike", 0, MagicSchool.DIVINATION, null, null),
    TSUNAMI("Tsunami", 8, MagicSchool.EVOCATION, DamageEnum.BLUDGEONING, Map.of(8, "12d10")),
    UNSEEN_SERVANT("Unseen Servant", 1, MagicSchool.CONJURATION, null, null),
    VAMPIRIC_TOUCH("Vampiric Touch", 3, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6")),
    VICIOUS_MOCKERY("Vicious Mockery", 0, MagicSchool.ENCHANTMENT, null, null),
    WALL_OF_FIRE("Wall of Fire", 4, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(4, "5d8")),
    WALL_OF_FORCE("Wall of Force", 5, MagicSchool.EVOCATION, null, null),
    WALL_OF_ICE("Wall of Ice", 6, MagicSchool.EVOCATION, DamageEnum.COLD, Map.of(6, "10d6", 7, "12d6", 8, "14d6", 9, "16d6")),
    WALL_OF_STONE("Wall of Stone", 5, MagicSchool.EVOCATION, null, null),
    WALL_OF_THORNS("Wall of Thorns", 6, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(6, "7d8", 7, "8d8", 8, "9d8", 9, "10d8")),
    WARDING_BOND("Warding Bond", 2, MagicSchool.ABJURATION, null, null),
    WATER_BREATHING("Water Breathing", 3, MagicSchool.TRANSMUTATION, null, null),
    WATER_WALK("Water Walk", 3, MagicSchool.TRANSMUTATION, null, null),
    WEB("Web", 2, MagicSchool.CONJURATION, null, null),
    WEIRD("Weird", 9, MagicSchool.ILLUSION, null, null),
    WIND_WALK("Wind Walk", 6, MagicSchool.TRANSMUTATION, null, null),
    WIND_WALL("Wind Wall", 3, MagicSchool.EVOCATION, DamageEnum.BLUDGEONING, Map.of(3, "3d8")),
    WISH("Wish", 9, MagicSchool.CONJURATION, null, null),
    WORD_OF_RECALL("Word of Recall", 6, MagicSchool.CONJURATION, null, null),
    ZONE_OF_TRUTH("Zone of Truth", 2, MagicSchool.ENCHANTMENT, null, null),
    BLADE_WARD("Blade Ward", 0, MagicSchool.ABJURATION, null, null),
    FRIENDS("Friends", 0, MagicSchool.ENCHANTMENT, null, null),
    ARMOR_OF_AGATHYS("Armor of Agathys", 1, MagicSchool.ABJURATION, DamageEnum.COLD, Map.of(1, "5")),
    ARMS_OF_HADAR("Arms of Hadar", 1, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(1, "2d6", 2, "3d6", 3, "4d6", 4, "5d6", 5, "6d6", 6, "7d6", 7, "8d6", 8, "9d6", 9, "10d6")),
    HEX("Hex", 1, MagicSchool.ENCHANTMENT, null, null),
    WITCH_BOLT("Witch Bolt", 1, MagicSchool.EVOCATION, DamageEnum.LIGHTNING, Map.of(1, "1d12", 2, "2d12", 3, "3d12", 4, "4d12", 5, "5d12", 6, "6d12", 7, "7d12", 8, "8d12", 9, "9d12")),
    CLOUD_OF_DAGGERS("Cloud of Daggers", 2, MagicSchool.CONJURATION, DamageEnum.SLASHING, Map.of(2, "4d4", 3, "5d4", 4, "6d4", 5, "7d4", 6, "8d4", 7, "9d4", 8, "10d4", 9, "11d4")),
    CROWN_OF_MADNESS("Crown of Madness", 2, MagicSchool.ENCHANTMENT, null, null),
    HUNGER_OF_HADAR("Hunger of Hadar", 3, MagicSchool.NECROMANCY, DamageEnum.COLD, Map.of(3, "2d6", 4, "3d6", 5, "4d6", 6, "5d6", 7, "6d6", 8, "7d6", 9, "8d6")),
    ARCANE_GATE("Arcane Gate", 6, MagicSchool.CONJURATION, null, null),
    GRASPING_VINE("Grasping Vine", 4, MagicSchool.CONJURATION, null, null),
    FEIGN_DEATH("Feign Death", 3, MagicSchool.NECROMANCY, null, null),
    BEAST_SENSE("Beast Sense", 2, MagicSchool.DIVINATION, null, null),
    THORN_WHIP("Thorn Whip", 0, MagicSchool.EVOCATION, DamageEnum.PIERCING, Map.of(0, "1d6", 1, "2d6", 2, "3d6", 3, "4d6", 4, "5d6", 5, "6d6", 6, "7d6", 7, "8d6", 8, "9d6")),
    DISSONANT_WHISPERS("Dissonant Whispers", 1, MagicSchool.ENCHANTMENT, DamageEnum.PSYCHIC, Map.of(1, "3d6", 2, "4d6", 3, "5d6", 4, "6d6", 5, "7d6", 6, "8d6", 7, "9d6", 8, "10d6", 9, "11d6")),
    TASHA_HIDEOUS_LAUGHTER("Tasha's Hideous Laughter", 1, MagicSchool.ENCHANTMENT, null, null),
    PHANTASMAL_FORCE("Phantasmal Force", 2, MagicSchool.ILLUSION, DamageEnum.PSYCHIC, Map.of(2, "1d6", 3, "2d6", 4, "3d6", 5, "4d6", 6, "5d6", 7, "6d6", 8, "7d6", 9, "8d6")),
    LEMUNDS_TINY_HUT("Leomund's Tiny Hut", 3, MagicSchool.EVOCATION, null, null),
    OTTOS_IRRESISTIBLE_DANCE("Otto's Irresistible Dance", 6, MagicSchool.ENCHANTMENT, null, null),
    MORDENKAINENS_MAGNIFICENT_MANSION("Mordenkainen's Magnificent Mansion", 7, MagicSchool.CONJURATION, null, null),
    MORDENKAINENS_SWORD("Mordenkainen's Sword", 7, MagicSchool.EVOCATION, DamageEnum.FORCE, Map.of(7, "3d10 + MOD", 8, "4d10 + MOD", 9, "5d10 + MOD")),
    POWER_WORD_HEAL("Power Word Heal", 9, MagicSchool.EVOCATION, null, null),
    SWIFT_QUIVER("Swift Quiver", 5, MagicSchool.TRANSMUTATION, null, null),
    CONJURE_VOLLEY("Conjure Volley", 5, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(5, "8d10", 6, "9d10", 7, "10d10", 8, "11d10", 9, "12d10")),
    LIGHTNING_ARROW("Lightning Arrow", 3, MagicSchool.EVOCATION, DamageEnum.LIGHTNING, Map.of(3, "4d8 + 4d6", 4, "5d8 + 4d6", 5, "6d8 + 4d6", 6, "7d8 + 4d6", 7, "8d8 + 4d6", 8, "9d8 + 4d6", 9, "10d8 + 4d6")),
    CONJURE_BARRAGE("Conjure Barrage", 3, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(3, "5d8", 4, "6d8", 5, "7d8", 6, "8d8", 7, "9d8", 8, "10d8", 9, "11d8")),
    CORDON_OF_ARROWS("Cordon of Arrows", 2, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(2, "2d8", 3, "3d8", 4, "4d8", 5, "5d8", 6, "6d8", 7, "7d8", 8, "8d8", 9, "9d8")),
    HAIL_OF_THORNS("Hail of Thorns", 1, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(1, "1d10", 2, "2d10", 3, "3d10", 4, "4d10", 5, "5d10", 6, "6d10", 7, "7d10", 8, "8d10", 9, "9d10")),
    ENSNARING_STRIKE("Ensnaring Strike", 1, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(1, "1d6", 2, "2d6", 3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6")),
    COMPELLED_DUEL("Compelled Duel", 1, MagicSchool.ENCHANTMENT, null, null),
    SEARING_SMITE("Searing Smite", 1, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(1, "1d6", 2, "2d6", 3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6")),
    THUNDEROUS_SMITE("Thunderous Smite", 1, MagicSchool.EVOCATION, DamageEnum.THUNDER, Map.of(1, "2d6", 2, "3d6", 3, "4d6", 4, "5d6", 5, "6d6", 6, "7d6", 7, "8d6", 8, "9d6")),
    WRATHFUL_SMITE("Wrathful Smite", 1, MagicSchool.EVOCATION, DamageEnum.PSYCHIC, Map.of(1, "1d6", 2, "2d6", 3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6")),
    AURA_OF_VITALITY("Aura of Vitality", 3, MagicSchool.EVOCATION, null, null),
    BLINDING_SMITE("Blinding Smite", 3, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(3, "3d8", 4, "4d8", 5, "5d8", 6, "6d8", 7, "7d8", 8, "8d8", 9, "9d8")),
    CRUSADERS_MANTLE("Crusader's Mantle", 3, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(3, "1d4", 4, "2d4", 5, "3d4", 6, "4d4", 7, "5d4", 8, "6d4", 9, "7d4")),
    ELEMENTAL_WEAPON("Elemental Weapon", 3, MagicSchool.TRANSMUTATION, null, null),
    AURA_OF_LIFE("Aura of Life", 4, MagicSchool.EVOCATION, null, null),
    AURA_OF_PURITY("Aura of Purity", 4, MagicSchool.EVOCATION, null, null),
    STAGGERING_SMITE("Staggering Smite", 4, MagicSchool.EVOCATION, DamageEnum.PSYCHIC, Map.of(4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6")),
    BANISHING_SMITE("Banishing Smite", 5, MagicSchool.EVOCATION, DamageEnum.FORCE, Map.of(5, "5d10", 6, "6d10", 7, "7d10", 8, "8d10", 9, "9d10")),
    CIRCLE_OF_POWER("Circle of Power", 5, MagicSchool.ABJURATION, null, null),
    DESTRUCTIVE_WAVE("Destructive Wave", 5, MagicSchool.EVOCATION, DamageEnum.THUNDER, Map.of(5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6")),
    CHROMATIC_ORB("Chromatic Orb", 1, MagicSchool.EVOCATION, null, Map.of(1, "3d8", 2, "4d8", 3, "5d8", 4, "6d8", 5, "7d8", 6, "8d8", 7, "9d8", 8, "10d8", 9, "11d8")),
    RAY_OF_SICKNESS("Ray of Sickness", 1, MagicSchool.NECROMANCY, DamageEnum.POISON, Map.of(1, "2d8", 2, "3d8", 3, "4d8", 4, "5d8", 5, "6d8", 6, "7d8", 7, "8d8", 8, "9d8")),
    TENSERS_FLOATING_DISC("Tenser's Floating Disc", 1, MagicSchool.CONJURATION, null, null),
    MELFS_ACID_ARROW("Melf's Acid Arrow", 2, MagicSchool.EVOCATION, DamageEnum.ACID, Map.of(2, "4d4", 3, "5d4", 4, "6d4", 5, "7d4", 6, "8d4", 7, "9d4", 8, "10d4", 9, "11d4")),
    NYSTULS_MAGIC_AURA("Nystul's Magic Aura", 2, MagicSchool.ILLUSION, null, null),
    EVARDS_BLACK_TENTACLES("Evard's Black Tentacles", 4, MagicSchool.CONJURATION, DamageEnum.BLUDGEONING, Map.of(4, "3d6", 5, "4d6", 6, "5d6", 7, "6d6", 8, "7d6", 9, "8d6")),
    LEOMUNDS_SECRET_CHEST("Leomund's Secret Chest", 4, MagicSchool.CONJURATION, null, null),
    MORDENKAINENS_FAITHFUL_HOUND("Mordenkainen's Faithful Hound", 4, MagicSchool.CONJURATION, DamageEnum.POISON, Map.of(4, "4d8", 5, "5d8", 6, "6d8", 7, "7d8", 8, "8d8", 9, "9d8")),
    MORDENKAINENS_PRIVATE_SANCTUM("Mordenkainen's Private Sanctum", 4, MagicSchool.ABJURATION, null, null),
    OTILUKES_RESILIENT_SPHERE("Otiluke's Resilient Sphere", 4, MagicSchool.EVOCATION, null, null),
    BIGBYS_HAND("Bigby's Hand", 5, MagicSchool.EVOCATION, null, null),
    RARYS_TELEPATHIC_BOND("Rary's Telepathic Bond", 5, MagicSchool.DIVINATION, null, null),
    TELEPATHY("Telepathy", 8, MagicSchool.DIVINATION, null, null),
    TRAP_THE_SOUL("Trap the Soul", 8, MagicSchool.ABJURATION, null, null),
    DRAWMIJS_INSTANT_SUMMONS("Drawmij's Instant Summons", 6, MagicSchool.CONJURATION, null, null),
    OTILUKES_FREEZING_SPHERE("Otiluke's Freezing Sphere", 6, MagicSchool.EVOCATION, DamageEnum.COLD, Map.of(6, "10d6", 7, "11d6", 8, "12d6", 9, "13d6"));

    private final String name;
    private final int level;
    private final MagicSchool school;
    private final DamageEnum damageType;
    private final Map<Integer, String> damageAtSlotLevel;

    SpellEnum(String name, int level, MagicSchool school, DamageEnum damageType, Map<Integer, String> damageAtSlotLevel) {
        this.name = name;
        this.level = level;
        this.school = school;
        this.damageType = damageType;
        this.damageAtSlotLevel = damageAtSlotLevel;
    }

    public Spell toSpell() {
        return new Spell(this.name(), level, school, damageType, damageAtSlotLevel != null ? damageAtSlotLevel.toString() : "");
    }

    public Spell toSpell(Integer npcLevel) {
        return new Spell(this.name(), level, school, damageType, getDamageForLevel(damageAtSlotLevel, npcLevel));
    }

    private String getDamageForLevel(Map<Integer, String> damageAtSlotLevel, Integer npcLevel) {
        if (damageAtSlotLevel == null || npcLevel == null) return "";
        for (int lvl = npcLevel; lvl >= 0; lvl--) {
            if (damageAtSlotLevel.containsKey(lvl)) {
                return damageAtSlotLevel.get(lvl);
            }
        }
        return "";
    }
}
