package com.raphaowl.dnd.enums;

import java.util.List;

import com.raphaowl.dnd.dtos.Spell;

import lombok.Getter;

@Getter
public enum SpellEnum2 {

    ACID_ARROW("acid-arrow", "Acid Arrow", 2, MagicSchool.EVOCATION, List.of(ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ACID_SPLASH("acid-splash", "Acid Splash", 0, MagicSchool.CONJURATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    AID("aid", "Aid", 2, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ALARM("alarm", "Alarm", 1, MagicSchool.ABJURATION, List.of(ClassEnum.RANGER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ALTER_SELF("alter-self", "Alter Self", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    ANIMAL_FRIENDSHIP("animal-friendship", "Animal Friendship", 1, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ANIMAL_MESSENGER("animal-messenger", "Animal Messenger", 2, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ANIMAL_SHAPES("animal-shapes", "Animal Shapes", 8, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    ANIMATE_DEAD("animate-dead", "Animate Dead", 3, MagicSchool.NECROMANCY, List.of(ClassEnum.CLERIC, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ANIMATE_OBJECTS("animate-objects", "Animate Objects", 5, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    ANTILIFE_SHELL("antilife-shell", "Antilife Shell", 5, MagicSchool.ABJURATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    ANTIMAGIC_FIELD("antimagic-field", "Antimagic Field", 8, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ANTIPATHY_SYMPATHY("antipathysympathy", "Antipathy/Sympathy", 8, MagicSchool.ENCHANTMENT, List.of(ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ARCANE_EYE("arcane-eye", "Arcane Eye", 4, MagicSchool.DIVINATION, List.of(ClassEnum.CLERIC, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ARCANE_HAND("arcane-hand", "Arcane Hand", 5, MagicSchool.EVOCATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ARCANE_LOCK("arcane-lock", "Arcane Lock", 2, MagicSchool.ABJURATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ARCANE_SWORD("arcane-sword", "Arcane Sword", 7, MagicSchool.EVOCATION, List.of(ClassEnum.BARD, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ARCANISTS_MAGIC_AURA("arcanists-magic-aura", "Arcanist's Magic Aura", 2, MagicSchool.ILLUSION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ASTRAL_PROJECTION("astral-projection", "Astral Projection", 9, MagicSchool.NECROMANCY, List.of(ClassEnum.CLERIC, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    AUGURY("augury", "Augury", 2, MagicSchool.DIVINATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    AWAKEN("awaken", "Awaken", 5, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    BANE("bane", "Bane", 1, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    BANISHMENT("banishment", "Banishment", 4, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    BARKSKIN("barkskin", "Barkskin", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    BEACON_OF_HOPE("beacon-of-hope", "Beacon of Hope", 3, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S)),
    BESTOW_CURSE("bestow-curse", "Bestow Curse", 3, MagicSchool.NECROMANCY, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    BLACK_TENTACLES("black-tentacles", "Black Tentacles", 4, MagicSchool.CONJURATION, List.of(ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    BLADE_BARRIER("blade-barrier", "Blade Barrier", 6, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S)),
    BLESS("bless", "Bless", 1, MagicSchool.ENCHANTMENT, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    BLIGHT("blight", "Blight", 4, MagicSchool.NECROMANCY, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    BLINDNESS_DEAFNESS("blindnessdeafness", "Blindness/Deafness", 2, MagicSchool.NECROMANCY, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    BLINK("blink", "Blink", 3, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    BLUR("blur", "Blur", 2, MagicSchool.ILLUSION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    BRANDING_SMITE("branding-smite", "Branding Smite", 2, MagicSchool.EVOCATION, List.of(ClassEnum.PALADIN), List.of(ComponentEnum.V)),
    BURNING_HANDS("burning-hands", "Burning Hands", 1, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    CALL_LIGHTNING("call-lightning", "Call Lightning", 3, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    CALM_EMOTIONS("calm-emotions", "Calm Emotions", 2, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.WARLOCK), List.of(ComponentEnum.V, ComponentEnum.S)),
    CHAIN_LIGHTNING("chain-lightning", "Chain Lightning", 6, MagicSchool.EVOCATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CHARM_PERSON("charm-person", "Charm Person", 1, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    CHILL_TOUCH("chill-touch", "Chill Touch", 0, MagicSchool.NECROMANCY, List.of(ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    CIRCLE_OF_DEATH("circle-of-death", "Circle of Death", 6, MagicSchool.NECROMANCY, List.of(ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CLAIRVOYANCE("clairvoyance", "Clairvoyance", 3, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CLONE("clone", "Clone", 8, MagicSchool.NECROMANCY, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CLOUDKILL("cloudkill", "Cloudkill", 5, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    COLOR_SPRAY("color-spray", "Color Spray", 1, MagicSchool.ILLUSION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    COMMAND("command", "Command", 1, MagicSchool.ENCHANTMENT, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN, ClassEnum.WARLOCK), List.of(ComponentEnum.V)),
    COMMUNE("commune", "Commune", 5, MagicSchool.DIVINATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    COMMUNE_WITH_NATURE("commune-with-nature", "Commune with Nature", 5, MagicSchool.DIVINATION, List.of(ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S)),
    COMPREHEND_LANGUAGES("comprehend-languages", "Comprehend Languages", 1, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    COMPULSION("compulsion", "Compulsion", 4, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    CONE_OF_COLD("cone-of-cold", "Cone of Cold", 5, MagicSchool.EVOCATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CONFUSION("confusion", "Confusion", 4, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CONJURE_ANIMALS("conjure-animals", "Conjure Animals", 3, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S)),
    CONJURE_CELESTIAL("conjure-celestial", "Conjure Celestial", 7, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S)),
    CONJURE_ELEMENTAL("conjure-elemental", "Conjure Elemental", 5, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CONJURE_FEY("conjure-fey", "Conjure Fey", 6, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID, ClassEnum.WARLOCK), List.of(ComponentEnum.V, ComponentEnum.S)),
    CONJURE_MINOR_ELEMENTALS("conjure-minor-elementals", "Conjure Minor Elementals", 4, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    CONJURE_WOODLAND_BEINGS("conjure-woodland-beings", "Conjure Woodland Beings", 4, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CONTACT_OTHER_PLANE("contact-other-plane", "Contact Other Plane", 5, MagicSchool.DIVINATION, List.of(ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    CONTAGION("contagion", "Contagion", 5, MagicSchool.NECROMANCY, List.of(ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    CONTINGENCY("contingency", "Contingency", 6, MagicSchool.EVOCATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CONTINUAL_FLAME("continual-flame", "Continual Flame", 2, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CONTROL_WATER("control-water", "Control Water", 4, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CONTROL_WEATHER("control-weather", "Control Weather", 8, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    COUNTERSPELL("counterspell", "Counterspell", 3, MagicSchool.ABJURATION, List.of(ClassEnum.PALADIN, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.S)),
    CREATE_FOOD_AND_WATER("create-food-and-water", "Create Food and Water", 3, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S)),
    CREATE_UNDEAD("create-undead", "Create Undead", 6, MagicSchool.NECROMANCY, List.of(ClassEnum.CLERIC, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CREATE_OR_DESTROY_WATER("create-or-destroy-water", "Create or Destroy Water", 1, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CREATION("creation", "Creation", 5, MagicSchool.ILLUSION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    CURE_WOUNDS("cure-wounds", "Cure Wounds", 1, MagicSchool.EVOCATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S)),
    DANCING_LIGHTS("dancing-lights", "Dancing Lights", 0, MagicSchool.EVOCATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    DARKNESS("darkness", "Darkness", 2, MagicSchool.EVOCATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.M)),
    DARKVISION("darkvision", "Darkvision", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.RANGER, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    DAYLIGHT("daylight", "Daylight", 3, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER, ClassEnum.SORCERER), List.of(ComponentEnum.V, ComponentEnum.S)),
    DEATH_WARD("death-ward", "Death Ward", 4, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S)),
    DELAYED_BLAST_FIREBALL("delayed-blast-fireball", "Delayed Blast Fireball", 7, MagicSchool.EVOCATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    DEMIPLANE("demiplane", "Demiplane", 8, MagicSchool.CONJURATION, List.of(ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.S)),
    DETECT_EVIL_AND_GOOD("detect-evil-and-good", "Detect Evil and Good", 1, MagicSchool.DIVINATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S)),
    DETECT_MAGIC("detect-magic", "Detect Magic", 1, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    DETECT_POISON_AND_DISEASE("detect-poison-and-disease", "Detect Poison and Disease", 1, MagicSchool.DIVINATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    DETECT_THOUGHTS("detect-thoughts", "Detect Thoughts", 2, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    DIMENSION_DOOR("dimension-door", "Dimension Door", 4, MagicSchool.CONJURATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.PALADIN, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    DISGUISE_SELF("disguise-self", "Disguise Self", 1, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    DISINTEGRATE("disintegrate", "Disintegrate", 6, MagicSchool.TRANSMUTATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    DISPEL_EVIL_AND_GOOD("dispel-evil-and-good", "Dispel Evil and Good", 5, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    DISPEL_MAGIC("dispel-magic", "Dispel Magic", 3, MagicSchool.ABJURATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    DIVINATION("divination", "Divination", 4, MagicSchool.DIVINATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    DIVINE_FAVOR("divine-favor", "Divine Favor", 1, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S)),
    DIVINE_WORD("divine-word", "Divine Word", 7, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V)),
    DOMINATE_BEAST("dominate-beast", "Dominate Beast", 4, MagicSchool.ENCHANTMENT, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK), List.of(ComponentEnum.V, ComponentEnum.S)),
    DOMINATE_MONSTER("dominate-monster", "Dominate Monster", 8, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    DOMINATE_PERSON("dominate-person", "Dominate Person", 5, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    DREAM("dream", "Dream", 5, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    DRUIDCRAFT("druidcraft", "Druidcraft", 0, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    EARTHQUAKE("earthquake", "Earthquake", 8, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ELDRITCH_BLAST("eldritch-blast", "Eldritch Blast", 0, MagicSchool.EVOCATION, List.of(ClassEnum.WARLOCK), List.of(ComponentEnum.V, ComponentEnum.S)),
    ENHANCE_ABILITY("enhance-ability", "Enhance Ability", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ENLARGE_REDUCE("enlargereduce", "Enlarge/Reduce", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ENTANGLE("entangle", "Entangle", 1, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    ENTHRALL("enthrall", "Enthrall", 2, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.WARLOCK), List.of(ComponentEnum.V, ComponentEnum.S)),
    ETHEREALNESS("etherealness", "Etherealness", 7, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    EXPEDITIOUS_RETREAT("expeditious-retreat", "Expeditious Retreat", 1, MagicSchool.TRANSMUTATION, List.of(ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    EYE_BITE("eye-bite", "Eye bite", 6, MagicSchool.NECROMANCY, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    EYEBITE("eyebite", "Eyebite", 6, MagicSchool.NECROMANCY, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    FABRICATE("fabricate", "Fabricate", 4, MagicSchool.TRANSMUTATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    FAERIE_FIRE("faerie-fire", "Faerie Fire", 1, MagicSchool.EVOCATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.WARLOCK), List.of(ComponentEnum.V)),
    FAITHFUL_HOUND("faithful-hound", "Faithful Hound", 4, MagicSchool.CONJURATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FALSE_LIFE("false-life", "False Life", 1, MagicSchool.NECROMANCY, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FEAR("fear", "Fear", 3, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FEATHER_FALL("feather-fall", "Feather Fall", 1, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.M)),
    FEEBLEMIND("feeblemind", "Feeblemind", 8, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FIND_FAMILIAR("find-familiar", "Find Familiar", 1, MagicSchool.CONJURATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FIND_STEED("find-steed", "Find Steed", 2, MagicSchool.CONJURATION, List.of(ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S)),
    FIND_TRAPS("find-traps", "Find Traps", 2, MagicSchool.DIVINATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S)),
    FIND_THE_PATH("find-the-path", "Find the Path", 6, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FINGER_OF_DEATH("finger-of-death", "Finger of Death", 7, MagicSchool.NECROMANCY, List.of(ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    FIRE_BOLT("fire-bolt", "Fire Bolt", 0, MagicSchool.EVOCATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    FIRE_SHIELD("fire-shield", "Fire Shield", 4, MagicSchool.EVOCATION, List.of(ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FIRE_STORM("fire-storm", "Fire Storm", 7, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER), List.of(ComponentEnum.V, ComponentEnum.S)),
    FIREBALL("fireball", "Fireball", 3, MagicSchool.EVOCATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FLAME_BLADE("flame-blade", "Flame Blade", 2, MagicSchool.EVOCATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FLAME_STRIKE("flame-strike", "Flame Strike", 5, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN, ClassEnum.WARLOCK), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FLAMING_SPHERE("flaming-sphere", "Flaming Sphere", 2, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FLESH_TO_STONE("flesh-to-stone", "Flesh to Stone", 6, MagicSchool.TRANSMUTATION, List.of(ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FLOATING_DISK("floating-disk", "Floating Disk", 1, MagicSchool.CONJURATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FLY("fly", "Fly", 3, MagicSchool.TRANSMUTATION, List.of(ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FOG_CLOUD("fog-cloud", "Fog Cloud", 1, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.RANGER, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    FORBIDDANCE("forbiddance", "Forbiddance", 6, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FORCECAGE("forcecage", "Forcecage", 7, MagicSchool.EVOCATION, List.of(ClassEnum.BARD, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FORESIGHT("foresight", "Foresight", 9, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FREEDOM_OF_MOVEMENT("freedom-of-movement", "Freedom of Movement", 4, MagicSchool.ABJURATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    FREEZING_SPHERE("freezing-sphere", "Freezing Sphere", 6, MagicSchool.EVOCATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    GASEOUS_FORM("gaseous-form", "Gaseous Form", 3, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    GATE("gate", "Gate", 9, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    GEAS("geas", "Geas", 5, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    GENTLE_REPOSE("gentle-repose", "Gentle Repose", 2, MagicSchool.NECROMANCY, List.of(ClassEnum.CLERIC, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    GIANT_INSECT("giant-insect", "Giant Insect", 4, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    GLIBNESS("glibness", "Glibness", 8, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.WARLOCK), List.of(ComponentEnum.V)),
    GLOBE_OF_INVULNERABILITY("globe-of-invulnerability", "Globe of Invulnerability", 6, MagicSchool.ABJURATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    GLYPH_OF_WARDING("glyph-of-warding", "Glyph of Warding", 3, MagicSchool.ABJURATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    GOODBERRY("goodberry", "Goodberry", 1, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    GREASE("grease", "Grease", 1, MagicSchool.CONJURATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    GREATER_INVISIBILITY("greater-invisibility", "Greater Invisibility", 4, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    GREATER_RESTORATION("greater-restoration", "Greater Restoration", 5, MagicSchool.ABJURATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    GUARDIAN_OF_FAITH("guardian-of-faith", "Guardian of Faith", 4, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V)),
    GUARDS_AND_WARDS("guards-and-wards", "Guards and Wards", 6, MagicSchool.ABJURATION, List.of(ClassEnum.BARD, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    GUIDANCE("guidance", "Guidance", 0, MagicSchool.DIVINATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    GUIDING_BOLT("guiding-bolt", "Guiding Bolt", 1, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S)),
    GUST_OF_WIND("gust-of-wind", "Gust of Wind", 2, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    HALLOW("hallow", "Hallow", 5, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.WARLOCK), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    HALLUCINATORY_TERRAIN("hallucinatory-terrain", "Hallucinatory Terrain", 4, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    HARM("harm", "Harm", 6, MagicSchool.NECROMANCY, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S)),
    HASTE("haste", "Haste", 3, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    HEAL("heal", "Heal", 6, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    HEALING_WORD("healing-word", "Healing Word", 1, MagicSchool.EVOCATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V)),
    HEAT_METAL("heat-metal", "Heat Metal", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    HELLISH_REBUKE("hellish-rebuke", "Hellish Rebuke", 1, MagicSchool.EVOCATION, List.of(ClassEnum.PALADIN, ClassEnum.WARLOCK), List.of(ComponentEnum.V, ComponentEnum.S)),
    HEROES_FEAST("heroes-feast", "Heroes' Feast", 6, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    HEROISM("heroism", "Heroism", 1, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S)),
    HIDEOUS_LAUGHTER("hideous-laughter", "Hideous Laughter", 1, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    HOLD_MONSTER("hold-monster", "Hold Monster", 5, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.PALADIN, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    HOLD_PERSON("hold-person", "Hold Person", 2, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    HOLY_AURA("holy-aura", "Holy Aura", 8, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    HUNTERS_MARK("hunters-mark", "Hunter's Mark", 1, MagicSchool.DIVINATION, List.of(ClassEnum.PALADIN, ClassEnum.RANGER), List.of(ComponentEnum.V)),
    HYPNOTIC_PATTERN("hypnotic-pattern", "Hypnotic Pattern", 3, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.S, ComponentEnum.M)),
    ICE_STORM("ice-storm", "Ice Storm", 4, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    IDENTIFY("identify", "Identify", 1, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ILLUSORY_SCRIPT("illusory-script", "Illusory Script", 1, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.S, ComponentEnum.M)),
    IMPRISONMENT("imprisonment", "Imprisonment", 9, MagicSchool.ABJURATION, List.of(ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    INCENDIARY_CLOUD("incendiary-cloud", "Incendiary Cloud", 8, MagicSchool.CONJURATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    INFLICT_WOUNDS("inflict-wounds", "Inflict Wounds", 1, MagicSchool.NECROMANCY, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S)),
    INSECT_PLAGUE("insect-plague", "Insect Plague", 5, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    INSTANT_SUMMONS("instant-summons", "Instant Summons", 6, MagicSchool.CONJURATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    INVISIBILITY("invisibility", "Invisibility", 2, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    IRRESISTIBLE_DANCE("irresistible-dance", "Irresistible Dance", 6, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    JUMP("jump", "Jump", 1, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.RANGER, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    KNOCK("knock", "Knock", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    LEGEND_LORE("legend-lore", "Legend Lore", 5, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    LESSER_RESTORATION("lesser-restoration", "Lesser Restoration", 2, MagicSchool.ABJURATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S)),
    LEVITATE("levitate", "Levitate", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    LIGHT("light", "Light", 0, MagicSchool.EVOCATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.M)),
    LIGHTNING_BOLT("lightning-bolt", "Lightning Bolt", 3, MagicSchool.EVOCATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    LOCATE_ANIMALS_OR_PLANTS("locate-animals-or-plants", "Locate Animals or Plants", 2, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    LOCATE_CREATURE("locate-creature", "Locate Creature", 4, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    LOCATE_OBJECT("locate-object", "Locate Object", 2, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    LONGSTRIDER("longstrider", "Longstrider", 1, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.RANGER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    MAGE_ARMOR("mage-armor", "Mage Armor", 1, MagicSchool.ABJURATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    MAGE_HAND("mage-hand", "Mage Hand", 0, MagicSchool.CONJURATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    MAGIC_CIRCLE("magic-circle", "Magic Circle", 3, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    MAGIC_JAR("magic-jar", "Magic Jar", 6, MagicSchool.NECROMANCY, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    MAGIC_MISSILE("magic-missile", "Magic Missile", 1, MagicSchool.EVOCATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    MAGIC_MOUTH("magic-mouth", "Magic Mouth", 2, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    MAGIC_WEAPON("magic-weapon", "Magic Weapon", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    MAGNIFICENT_MANSION("magnificent-mansion", "Magnificent Mansion", 7, MagicSchool.CONJURATION, List.of(ClassEnum.BARD, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    MAJOR_IMAGE("major-image", "Major Image", 3, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    MASS_CURE_WOUNDS("mass-cure-wounds", "Mass Cure Wounds", 5, MagicSchool.CONJURATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    MASS_HEAL("mass-heal", "Mass Heal", 9, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S)),
    MASS_HEALING_WORD("mass-healing-word", "Mass Healing Word", 3, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V)),
    MASS_SUGGESTION("mass-suggestion", "Mass Suggestion", 6, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.M)),
    MAZE("maze", "Maze", 8, MagicSchool.CONJURATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    MELD_INTO_STONE("meld-into-stone", "Meld into Stone", 3, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    MENDING("mending", "Mending", 0, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    MESSAGE("message", "Message", 0, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    METEOR_SWARM("meteor-swarm", "Meteor Swarm", 9, MagicSchool.EVOCATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    MIND_BLANK("mind-blank", "Mind Blank", 8, MagicSchool.ABJURATION, List.of(ClassEnum.BARD, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    MINOR_ILLUSION("minor-illusion", "Minor Illusion", 0, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.S, ComponentEnum.M)),
    MIRAGE_ARCANE("mirage-arcane", "Mirage Arcane", 7, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    MIRROR_IMAGE("mirror-image", "Mirror Image", 2, MagicSchool.ILLUSION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    MISLEAD("mislead", "Mislead", 5, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.WIZARD), List.of(ComponentEnum.S)),
    MISTY_STEP("misty-step", "Misty Step", 2, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    MODIFY_MEMORY("modify-memory", "Modify Memory", 5, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    MOONBEAM("moonbeam", "Moonbeam", 2, MagicSchool.EVOCATION, List.of(ClassEnum.DRUID, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    MOVE_EARTH("move-earth", "Move Earth", 6, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    NONDETECTION("nondetection", "Nondetection", 3, MagicSchool.ABJURATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.RANGER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    PASS_WITHOUT_TRACE("pass-without-trace", "Pass without Trace", 2, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    PASSWALL("passwall", "Passwall", 5, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    PHANTASMAL_KILLER("phantasmal-killer", "Phantasmal Killer", 4, MagicSchool.ILLUSION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    PHANTOM_STEED("phantom-steed", "Phantom Steed", 3, MagicSchool.ILLUSION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    PLANAR_ALLY("planar-ally", "Planar Ally", 6, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S)),
    PLANAR_BINDING("planar-binding", "Planar Binding", 5, MagicSchool.ABJURATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    PLANE_SHIFT("plane-shift", "Plane Shift", 7, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    PLANT_GROWTH("plant-growth", "Plant Growth", 3, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER, ClassEnum.WARLOCK), List.of(ComponentEnum.V, ComponentEnum.S)),
    POISON_SPRAY("poison-spray", "Poison Spray", 0, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    POLYMORPH("polymorph", "Polymorph", 4, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    POWER_WORD_KILL("power-word-kill", "Power Word Kill", 9, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    POWER_WORD_STUN("power-word-stun", "Power Word Stun", 8, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    PRAYER_OF_HEALING("prayer-of-healing", "Prayer of Healing", 2, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V)),
    PRESTIDIGITATION("prestidigitation", "Prestidigitation", 0, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    PRISMATIC_SPRAY("prismatic-spray", "Prismatic Spray", 7, MagicSchool.EVOCATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    PRISMATIC_WALL("prismatic-wall", "Prismatic Wall", 9, MagicSchool.ABJURATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    PRIVATE_SANCTUM("private-sanctum", "Private Sanctum", 4, MagicSchool.ABJURATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    PRODUCE_FLAME("produce-flame", "Produce Flame", 0, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    PROGRAMMED_ILLUSION("programmed-illusion", "Programmed Illusion", 6, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    PROJECT_IMAGE("project-image", "Project Image", 7, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    PROTECTION_FROM_ENERGY("protection-from-energy", "Protection from Energy", 3, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    PROTECTION_FROM_EVIL_AND_GOOD("protection-from-evil-and-good", "Protection from Evil and Good", 1, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    PROTECTION_FROM_POISON("protection-from-poison", "Protection from Poison", 2, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S)),
    PURIFY_FOOD_AND_DRINK("purify-food-and-drink", "Purify Food and Drink", 1, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S)),
    RAISE_DEAD("raise-dead", "Raise Dead", 5, MagicSchool.NECROMANCY, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    RAY_OF_ENFEEBLEMENT("ray-of-enfeeblement", "Ray of Enfeeblement", 2, MagicSchool.NECROMANCY, List.of(ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    RAY_OF_FROST("ray-of-frost", "Ray of Frost", 0, MagicSchool.EVOCATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    RAY_OF_SICKNESS("ray-of-sickness", "Ray of Sickness", 1, MagicSchool.NECROMANCY, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    REGENERATE("regenerate", "Regenerate", 7, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    REINCARNATE("reincarnate", "Reincarnate", 5, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    REMOVE_CURSE("remove-curse", "Remove Curse", 3, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    RESILIENT_SPHERE("resilient-sphere", "Resilient Sphere", 4, MagicSchool.EVOCATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    RESISTANCE("resistance", "Resistance", 0, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    RESURRECTION("resurrection", "Resurrection", 7, MagicSchool.NECROMANCY, List.of(ClassEnum.BARD, ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    REVERSE_GRAVITY("reverse-gravity", "Reverse Gravity", 7, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    REVIVIFY("revivify", "Revivify", 3, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    ROPE_TRICK("rope-trick", "Rope Trick", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SACRED_FLAME("sacred-flame", "Sacred Flame", 0, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S)),
    SANCTUARY("sanctuary", "Sanctuary", 1, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SCORCHING_RAY("scorching-ray", "Scorching Ray", 2, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    SCRYING("scrying", "Scrying", 5, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SECRET_CHEST("secret-chest", "Secret Chest", 4, MagicSchool.CONJURATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SEE_INVISIBILITY("see-invisibility", "See Invisibility", 2, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SEEMING("seeming", "Seeming", 5, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    SENDING("sending", "Sending", 3, MagicSchool.EVOCATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SEQUESTER("sequester", "Sequester", 7, MagicSchool.TRANSMUTATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SHAPECHANGE("shapechange", "Shapechange", 9, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SHATTER("shatter", "Shatter", 2, MagicSchool.EVOCATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SHIELD("shield", "Shield", 1, MagicSchool.ABJURATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    SHIELD_OF_FAITH("shield-of-faith", "Shield of Faith", 1, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SHILLELAGH("shillelagh", "Shillelagh", 0, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SHOCKING_GRASP("shocking-grasp", "Shocking Grasp", 0, MagicSchool.EVOCATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    SILENCE("silence", "Silence", 2, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S)),
    SILENT_IMAGE("silent-image", "Silent Image", 1, MagicSchool.ILLUSION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SIMULACRUM("simulacrum", "Simulacrum", 7, MagicSchool.ILLUSION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SLEEP("sleep", "Sleep", 1, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SLEET_STORM("sleet-storm", "Sleet Storm", 3, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SLOW("slow", "Slow", 3, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SPARE_THE_DYING("spare-the-dying", "Spare the Dying", 0, MagicSchool.NECROMANCY, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S)),
    SPEAK_WITH_ANIMALS("speak-with-animals", "Speak with Animals", 1, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S)),
    SPEAK_WITH_DEAD("speak-with-dead", "Speak with Dead", 3, MagicSchool.NECROMANCY, List.of(ClassEnum.BARD, ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SPEAK_WITH_PLANTS("speak-with-plants", "Speak with Plants", 3, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S)),
    SPIDER_CLIMB("spider-climb", "Spider Climb", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SPIKE_GROWTH("spike-growth", "Spike Growth", 2, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SPIRIT_GUARDIANS("spirit-guardians", "Spirit Guardians", 3, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SPIRITUAL_WEAPON("spiritual-weapon", "Spiritual Weapon", 2, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S)),
    STINKING_CLOUD("stinking-cloud", "Stinking Cloud", 3, MagicSchool.CONJURATION, List.of(ClassEnum.BARD, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    STONE_SHAPE("stone-shape", "Stone Shape", 4, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    STONESKIN("stoneskin", "Stoneskin", 4, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    STORM_OF_VENGEANCE("storm-of-vengeance", "Storm of Vengeance", 9, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    SUGGESTION("suggestion", "Suggestion", 2, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.M)),
    SUNBEAM("sunbeam", "Sunbeam", 6, MagicSchool.EVOCATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SUNBURST("sunburst", "Sunburst", 8, MagicSchool.EVOCATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    SYMBOL("symbol", "Symbol", 7, MagicSchool.ABJURATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    TELEKINESIS("telekinesis", "Telekinesis", 5, MagicSchool.TRANSMUTATION, List.of(ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    TELEPATHIC_BOND("telepathic-bond", "Telepathic Bond", 5, MagicSchool.DIVINATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    TELEPORT("teleport", "Teleport", 7, MagicSchool.CONJURATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    TELEPORTATION_CIRCLE("teleportation-circle", "Teleportation Circle", 5, MagicSchool.CONJURATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.M)),
    THAUMATURGY("thaumaturgy", "Thaumaturgy", 0, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V)),
    THUNDERWAVE("thunderwave", "Thunderwave", 1, MagicSchool.EVOCATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    TIME_STOP("time-stop", "Time Stop", 9, MagicSchool.TRANSMUTATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    TINY_HUT("tiny-hut", "Tiny Hut", 3, MagicSchool.EVOCATION, List.of(ClassEnum.BARD, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    TONGUES("tongues", "Tongues", 3, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.M)),
    TRANSPORT_VIA_PLANTS("transport-via-plants", "Transport via Plants", 6, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S)),
    TREE_STRIDE("tree-stride", "Tree Stride", 5, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.PALADIN, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S)),
    TRUE_POLYMORPH("true-polymorph", "True Polymorph", 9, MagicSchool.TRANSMUTATION, List.of(ClassEnum.BARD, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    TRUE_RESURRECTION("true-resurrection", "True Resurrection", 9, MagicSchool.NECROMANCY, List.of(ClassEnum.CLERIC, ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    TRUE_SEEING("true-seeing", "True Seeing", 6, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    TRUE_STRIKE("true-strike", "True Strike", 0, MagicSchool.DIVINATION, List.of(ClassEnum.BARD, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.S)),
    UNSEEN_SERVANT("unseen-servant", "Unseen Servant", 1, MagicSchool.CONJURATION, List.of(ClassEnum.BARD, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    VAMPIRIC_TOUCH("vampiric-touch", "Vampiric Touch", 3, MagicSchool.NECROMANCY, List.of(ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    VICIOUS_MOCKERY("vicious-mockery", "Vicious Mockery", 0, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD), List.of(ComponentEnum.V)),
    WALL_OF_FIRE("wall-of-fire", "Wall of Fire", 4, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WARLOCK, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    WALL_OF_FORCE("wall-of-force", "Wall of Force", 5, MagicSchool.EVOCATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    WALL_OF_ICE("wall-of-ice", "Wall of Ice", 6, MagicSchool.EVOCATION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    WALL_OF_STONE("wall-of-stone", "Wall of Stone", 5, MagicSchool.EVOCATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    WALL_OF_THORNS("wall-of-thorns", "Wall of Thorns", 6, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    WARDING_BOND("warding-bond", "Warding Bond", 2, MagicSchool.ABJURATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    WATER_BREATHING("water-breathing", "Water Breathing", 3, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID, ClassEnum.RANGER, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    WATER_WALK("water-walk", "Water Walk", 3, MagicSchool.TRANSMUTATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.RANGER, ClassEnum.SORCERER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    WEB("web", "Web", 2, MagicSchool.CONJURATION, List.of(ClassEnum.DRUID, ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    WEIRD("weird", "Weird", 9, MagicSchool.ILLUSION, List.of(ClassEnum.WIZARD), List.of(ComponentEnum.V, ComponentEnum.S)),
    WIND_WALK("wind-walk", "Wind Walk", 6, MagicSchool.TRANSMUTATION, List.of(ClassEnum.DRUID), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    WIND_WALL("wind-wall", "Wind Wall", 3, MagicSchool.EVOCATION, List.of(ClassEnum.CLERIC, ClassEnum.DRUID, ClassEnum.RANGER), List.of(ComponentEnum.V, ComponentEnum.S, ComponentEnum.M)),
    WISH("wish", "Wish", 9, MagicSchool.CONJURATION, List.of(ClassEnum.SORCERER, ClassEnum.WIZARD), List.of(ComponentEnum.V)),
    WORD_OF_RECALL("word-of-recall", "Word of Recall", 6, MagicSchool.CONJURATION, List.of(ClassEnum.CLERIC), List.of(ComponentEnum.V)),
    ZONE_OF_TRUTH("zone-of-truth", "Zone of Truth", 2, MagicSchool.ENCHANTMENT, List.of(ClassEnum.BARD, ClassEnum.CLERIC, ClassEnum.PALADIN), List.of(ComponentEnum.V, ComponentEnum.S));

    private String id;
    private String name;
    private int level;
    private MagicSchool school;
    private List<ClassEnum> classes;
    private List<ComponentEnum> components;

    SpellEnum2(String id, String name, int level, MagicSchool school, List<ClassEnum> classEnum, List<ComponentEnum> componentEnums) {
        this.id = id;
        this.name = name;
        this.level = level;
        this.school = school;
        this.classes = classEnum;
        this.components = componentEnums;
    }

    public Spell toSpell() {
        return new Spell(name, level, school, null, "");
    }
}
