package com.raphaowl.dnd.enums;

import java.util.List;
import java.util.Map;

import com.raphaowl.dnd.dtos.Spell;

import lombok.Getter;

@Getter
public enum SpellEnum {
    ACID_ARROW("Acid Arrow", 2, MagicSchool.EVOCATION, DamageEnum.ACID, Map.of(2, "2d4", 3, "3d4", 4, "4d4", 5, "5d4", 6, "6d4", 7, "7d4", 8, "8d4", 9, "9d4"), List.of(VersionEnum.V2024), List.of(ComponentEnum.V)),
    ACID_SPLASH("Acid Splash", 0, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    AID("Aid", 2, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ALARM("Alarm", 1, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ALTER_SELF("Alter Self", 2, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ANIMAL_FRIENDSHIP("Animal Friendship", 1, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ANIMAL_MESSENGER("Animal Messenger", 2, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ANIMAL_SHAPES("Animal Shapes", 8, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ANIMATE_DEAD("Animate Dead", 3, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ANIMATE_OBJECTS("Animate Objects", 5, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ANTILIFE_SHELL("Antilife Shell", 5, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ANTIMAGIC_FIELD("Antimagic Field", 8, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ANTIPATHY_SYMPATHY("Antipathy/Sympathy", 8, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ARCANE_EYE("Arcane Eye", 4, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ARCANE_GATE("Arcane Gate", 6, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    ARCANE_HAND("Arcane Hand", 5, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2024), List.of(ComponentEnum.V)),
    ARCANE_LOCK("Arcane Lock", 2, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ARCANISTS_MAGIC_AURA("Arcanist's Magic Aura", 1, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2024), List.of(ComponentEnum.V)),
    ARMOR_OF_AGATHYS("Armor of Agathys", 1, MagicSchool.ABJURATION, DamageEnum.COLD, Map.of(1, "5"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    ARMS_OF_HADAR("Arms of Hadar", 1, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(1, "2d6", 2, "3d6", 3, "4d6", 4, "5d6", 5, "6d6", 6, "7d6", 7, "8d6", 8, "9d6", 9, "10d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    ASTRAL_PROJECTION("Astral Projection", 9, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    AUGURY("Augury", 2, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    AURA_OF_LIFE("Aura of Life", 4, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    AURA_OF_PURITY("Aura of Purity", 4, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    AURA_OF_VITALITY("Aura of Vitality", 3, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    AWAKEN("Awaken", 5, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BANE("Bane", 1, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BANISHING_SMITE("Banishing Smite", 5, MagicSchool.EVOCATION, DamageEnum.FORCE, Map.of(5, "5d10", 6, "6d10", 7, "7d10", 8, "8d10", 9, "9d10"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    BANISHMENT("Banishment", 4, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BARKSKIN("Barkskin", 2, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BEACON_OF_HOPE("Beacon of Hope", 3, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BEAST_SENSE("Beast Sense", 2, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    BESTOW_CURSE("Bestow Curse", 3, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BIGBYS_HAND("Bigby's Hand", 5, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    BLACK_TENTACLES("Black Tentacles", 4, MagicSchool.CONJURATION, DamageEnum.BLUDGEONING, Map.of(4, "3d6", 5, "4d6", 6, "5d6", 7, "6d6", 8, "7d6", 9, "8d6"), List.of(VersionEnum.V2024), List.of(ComponentEnum.V)),
    BLADE_BARRIER("Blade Barrier", 6, MagicSchool.EVOCATION, DamageEnum.SLASHING, Map.of(6, "6d10"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BLADE_WARD("Blade Ward", 0, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    BLESS("Bless", 1, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BLIGHT("Blight", 4, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(4, "8d8", 5, "9d8", 6, "10d8", 7, "11d8", 8, "12d8", 9, "13d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BLINDING_SMITE("Blinding Smite", 3, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(3, "3d8", 4, "4d8", 5, "5d8", 6, "6d8", 7, "7d8", 8, "8d8", 9, "9d8"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    BLINDNESS_DEAFNESS("Blindness/Deafness", 2, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BLINK("Blink", 3, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BLUR("Blur", 2, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BRANDING_SMITE("Branding Smite", 2, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(2, "2d6", 3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    BURNING_HANDS("Burning Hands", 1, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(1, "3d6", 2, "4d6", 3, "5d6", 4, "6d6", 5, "7d6", 6, "8d6", 7, "9d6", 8, "10d6", 9, "11d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CALL_LIGHTNING("Call Lightning", 3, MagicSchool.CONJURATION, DamageEnum.LIGHTNING, Map.of(3, "3d10", 4, "4d10", 5, "5d10", 6, "6d10", 7, "7d10", 8, "8d10", 9, "9d10"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CALM_EMOTIONS("Calm Emotions", 2, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CHAIN_LIGHTNING("Chain Lightning", 6, MagicSchool.EVOCATION, DamageEnum.LIGHTNING, Map.of(6, "10d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CHARM_PERSON("Charm Person", 1, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CHILL_TOUCH("Chill Touch", 0, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CHROMATIC_ORB("Chromatic Orb", 1, MagicSchool.EVOCATION, null, Map.of(1, "3d8", 2, "4d8", 3, "5d8", 4, "6d8", 5, "7d8", 6, "8d8", 7, "9d8", 8, "10d8", 9, "11d8"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    CIRCLE_OF_DEATH("Circle of Death", 6, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(6, "8d6", 7, "10d6", 8, "12d6", 9, "14d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CIRCLE_OF_POWER("Circle of Power", 5, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    CLAIRVOYANCE("Clairvoyance", 3, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CLONE("Clone", 8, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CLOUDKILL("Cloudkill", 5, MagicSchool.CONJURATION, DamageEnum.POISON, Map.of(5, "5d8", 6, "6d8", 7, "7d8", 8, "8d8", 9, "9d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CLOUD_OF_DAGGERS("Cloud of Daggers", 2, MagicSchool.CONJURATION, DamageEnum.SLASHING, Map.of(2, "4d4", 3, "5d4", 4, "6d4", 5, "7d4", 6, "8d4", 7, "9d4", 8, "10d4", 9, "11d4"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    COLOR_SPRAY("Color Spray", 1, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    COMMAND("Command", 1, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    COMMUNE("Commune", 5, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    COMMUNE_WITH_NATURE("Commune With Nature", 5, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    COMPELLED_DUEL("Compelled Duel", 1, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    COMPREHEND_LANGUAGES("Comprehend Languages", 1, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    COMPULSION("Compulsion", 4, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONE_OF_COLD("Cone of Cold", 5, MagicSchool.EVOCATION, DamageEnum.COLD, Map.of(5, "8d8", 6, "9d8", 7, "10d8", 8, "11d8", 9, "12d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONFUSION("Confusion", 4, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONJURE_ANIMALS("Conjure Animals", 3, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONJURE_BARRAGE("Conjure Barrage", 3, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(3, "5d8", 4, "6d8", 5, "7d8", 6, "8d8", 7, "9d8", 8, "10d8", 9, "11d8"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    CONJURE_CELESTIAL("Conjure Celestial", 7, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONJURE_ELEMENTAL("Conjure Elemental", 5, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONJURE_FEY("Conjure Fey", 6, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONJURE_MINOR_ELEMENTALS("Conjure Minor Elementals", 4, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONJURE_VOLLEY("Conjure Volley", 5, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(5, "8d10", 6, "9d10", 7, "10d10", 8, "11d10", 9, "12d10"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    CONJURE_WOODLAND_BEINGS("Conjure Woodland Beings", 4, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONTACT_OTHER_PLANE("Contact Other Plane", 5, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONTAGION("Contagion", 5, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONTINGENCY("Contingency", 6, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONTINUAL_FLAME("Continual Flame", 2, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONTROL_WATER("Control Water", 4, MagicSchool.TRANSMUTATION, DamageEnum.BLUDGEONING, Map.of(4, "2d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CONTROL_WEATHER("Control Weather", 8, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CORDON_OF_ARROWS("Cordon of Arrows", 2, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(2, "2d8", 3, "3d8", 4, "4d8", 5, "5d8", 6, "6d8", 7, "7d8", 8, "8d8", 9, "9d8"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    COUNTERSPELL("Counterspell", 3, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CREATE_FOOD_AND_WATER("Create Food and Water", 3, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CREATE_OR_DESTROY_WATER("Create or Destroy Water", 1, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CREATE_UNDEAD("Create Undead", 6, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CREATION("Creation", 5, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    CROWN_OF_MADNESS("Crown of Madness", 2, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    CRUSADERS_MANTLE("Crusader's Mantle", 3, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(3, "1d4", 4, "2d4", 5, "3d4", 6, "4d4", 7, "5d4", 8, "6d4", 9, "7d4"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    CURE_WOUNDS("Cure Wounds", 1, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DANCING_LIGHTS("Dancing Lights", 0, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DARKNESS("Darkness", 2, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DARKVISION("Darkvision", 2, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DAYLIGHT("Daylight", 3, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DEATH_WARD("Death Ward", 4, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DELAYED_BLAST_FIREBALL("Delayed Blast Fireball", 7, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(7, "12d6", 8, "13d6", 9, "14d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DEMIPLANE("Demiplane", 8, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DESTRUCTIVE_WAVE("Destructive Wave", 5, MagicSchool.EVOCATION, DamageEnum.THUNDER, Map.of(5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    DETECT_EVIL_AND_GOOD("Detect Evil and Good", 1, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DETECT_MAGIC("Detect Magic", 1, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DETECT_POISON_AND_DISEASE("Detect Poison and Disease", 1, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DETECT_THOUGHTS("Detect Thoughts", 2, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DIMENSION_DOOR("Dimension Door", 4, MagicSchool.CONJURATION, DamageEnum.FORCE, Map.of(4, "4d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DISGUISE_SELF("Disguise Self", 1, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DISINTEGRATE("Disintegrate", 6, MagicSchool.TRANSMUTATION, DamageEnum.FORCE, Map.of(6, "10d6 + 40"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DISPEL_EVIL_AND_GOOD("Dispel Evil and Good", 5, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DISPEL_MAGIC("Dispel Magic", 3, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DISSONANT_WHISPERS("Dissonant Whispers", 1, MagicSchool.ENCHANTMENT, DamageEnum.PSYCHIC, Map.of(1, "3d6", 2, "4d6", 3, "5d6", 4, "6d6", 5, "7d6", 6, "8d6", 7, "9d6", 8, "10d6", 9, "11d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    DIVINATION("Divination", 4, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DIVINE_FAVOR("Divine Favor", 1, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(1, "1d4"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DIVINE_WORD("Divine Word", 7, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DOMINATE_BEAST("Dominate Beast", 4, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DOMINATE_MONSTER("Dominate Monster", 8, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DOMINATE_PERSON("Dominate Person", 5, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DRAWMIJS_INSTANT_SUMMONS("Drawmij's Instant Summons", 6, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    DREAM("Dream", 5, MagicSchool.ILLUSION, DamageEnum.PSYCHIC, Map.of(5, "3d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    DRUIDCRAFT("Druidcraft", 0, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    EARTHQUAKE("Earthquake", 8, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ELDRITCH_BLAST("Eldritch Blast", 0, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ELEMENTAL_WEAPON("Elemental Weapon", 3, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    ENHANCE_ABILITY("Enhance Ability", 2, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ENLARGE_REDUCE("Enlarge/Reduce", 2, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ENSNARING_STRIKE("Ensnaring Strike", 1, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(1, "1d6", 2, "2d6", 3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    ENTANGLE("Entangle", 1, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ENTHRALL("Enthrall", 2, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ETHEREALNESS("Etherealness", 7, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    EVARDS_BLACK_TENTACLES("Evard's Black Tentacles", 4, MagicSchool.CONJURATION, DamageEnum.BLUDGEONING, Map.of(4, "3d6", 5, "4d6", 6, "5d6", 7, "6d6", 8, "7d6", 9, "8d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    EXPEDITIOUS_RETREAT("Expeditious Retreat", 1, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    EYEBITE("Eyebite", 6, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FABRICATE("Fabricate", 4, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FAERIE_FIRE("Faerie Fire", 1, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FAITHFUL_HOUND("Faithful Hound", 4, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(4, "4d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FALSE_LIFE("False Life", 1, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FEAR("Fear", 3, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FEATHER_FALL("Feather Fall", 1, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FEEBLEMIND("Feeblemind", 8, MagicSchool.ENCHANTMENT, DamageEnum.PSYCHIC, Map.of(8, "4d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FEIGN_DEATH("Feign Death", 3, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    FIND_FAMILIAR("Find Familiar", 1, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FIND_STEED("Find Steed", 2, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FIND_THE_PATH("Find the Path", 6, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FIND_TRAPS("Find Traps", 2, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FINGER_OF_DEATH("Finger of Death", 7, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(7, "7d8 + 30"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FIREBALL("Fireball", 3, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(3, "8d6", 4, "9d6", 5, "10d6", 6, "11d6", 7, "12d6", 8, "13d6", 9, "14d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FIRE_BOLT("Fire Bolt", 0, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FIRE_SHIELD("Fire Shield", 4, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(4, "2d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FIRE_STORM("Fire Storm", 7, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(7, "7d10"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FLAME_BLADE("Flame Blade", 2, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(2, "3d6", 4, "4d6", 6, "5d6", 8, "6d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FLAME_STRIKE("Flame Strike", 5, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(5, "4d6 + 4d6", 6, "4d6 + 5d6", 7, "4d6 + 6d6", 8, "4d6 + 7d6", 9, "4d6 + 8d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FLAMING_SPHERE("Flaming Sphere", 2, MagicSchool.CONJURATION, DamageEnum.FIRE, Map.of(2, "2d6", 3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FLESH_TO_STONE("Flesh to Stone", 6, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FLOATING_DISK("Floating Disk", 1, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2024), List.of(ComponentEnum.V)),
    FLY("Fly", 3, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FOG_CLOUD("Fog Cloud", 1, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FORBIDDANCE("Forbiddance", 6, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FORCECAGE("Forcecage", 7, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FORESIGHT("Foresight", 9, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FREEDOM_OF_MOVEMENT("Freedom of Movement", 4, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FREEZING_SPHERE("Freezing Sphere", 6, MagicSchool.EVOCATION, DamageEnum.COLD, Map.of(6, "10d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    FRIENDS("Friends", 0, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    GASEOUS_FORM("Gaseous Form", 3, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GATE("Gate", 9, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GEAS("Geas", 5, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GENTLE_REPOSE("Gentle Repose", 2, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GIANT_INSECT("Giant Insect", 4, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GLIBNESS("Glibness", 8, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GLOBE_OF_INVULNERABILITY("Globe of Invulnerability", 6, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GLYPH_OF_WARDING("Glyph of Warding", 3, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GOODBERRY("Goodberry", 1, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GRASPING_VINE("Grasping Vine", 4, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    GREASE("Grease", 1, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GREATER_INVISIBILITY("Greater Invisibility", 4, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GREATER_RESTORATION("Greater Restoration", 5, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GUARDIAN_OF_FAITH("Guardian of Faith", 4, MagicSchool.CONJURATION, DamageEnum.RADIANT, Map.of(4, "20"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GUARDS_AND_WARDS("Guards and Wards", 6, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GUIDANCE("Guidance", 0, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GUIDING_BOLT("Guiding Bolt", 1, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(1, "4d6", 2, "5d6", 3, "6d6", 4, "7d6", 5, "8d6", 6, "9d6", 7, "10d6", 8, "11d6", 9, "12d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    GUST_OF_WIND("Gust of Wind", 2, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HAIL_OF_THORNS("Hail of Thorns", 1, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(1, "1d10", 2, "2d10", 3, "3d10", 4, "4d10", 5, "5d10", 6, "6d10", 7, "7d10", 8, "8d10", 9, "9d10"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    HALLOW("Hallow", 5, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HALLUCINATORY_TERRAIN("Hallucinatory Terrain", 4, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HARM("Harm", 6, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(6, "14d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HASTE("Haste", 3, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HEAL("Heal", 6, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HEALING_WORD("Healing Word", 1, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HEAT_METAL("Heat Metal", 2, MagicSchool.TRANSMUTATION, DamageEnum.FIRE, Map.of(2, "2d8", 3, "3d8", 4, "4d8", 5, "5d8", 6, "6d8", 7, "7d8", 8, "8d8", 9, "9d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HELLISH_REBUKE("Hellish Rebuke", 1, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(1, "2d10", 2, "3d10", 3, "4d10", 4, "5d10", 5, "6d10", 6, "7d10", 7, "8d10", 8, "9d10", 9, "10d10"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HEROES_FEAST("Heroes' Feast", 6, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HEROISM("Heroism", 1, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HEX("Hex", 1, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    HIDEOUS_LAUGHTER("Hideous Laughter", 1, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2024), List.of(ComponentEnum.V)),
    HOLD_MONSTER("Hold Monster", 5, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HOLD_PERSON("Hold Person", 2, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HOLY_AURA("Holy Aura", 8, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HUNGER_OF_HADAR("Hunger of Hadar", 3, MagicSchool.NECROMANCY, DamageEnum.COLD, Map.of(3, "2d6", 4, "3d6", 5, "4d6", 6, "5d6", 7, "6d6", 8, "7d6", 9, "8d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    HUNTERS_MARK("Hunter's Mark", 1, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    HYPNOTIC_PATTERN("Hypnotic Pattern", 3, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ICE_STORM("Ice Storm", 4, MagicSchool.EVOCATION, DamageEnum.BLUDGEONING, Map.of(4, "2d8 + 4d6", 5, "3d8 + 4d6", 6, "4d8 + 4d6", 7, "5d8 + 4d6", 8, "6d8 + 4d6", 9, "7d8 + 4d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    IDENTIFY("Identify", 1, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ILLUSORY_SCRIPT("Illusory Script", 1, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    IMPRISONMENT("Imprisonment", 9, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    INCENDIARY_CLOUD("Incendiary Cloud", 8, MagicSchool.CONJURATION, DamageEnum.FIRE, Map.of(8, "10d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    INFLICT_WOUNDS("Inflict Wounds", 1, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(1, "3d10", 2, "4d10", 3, "5d10", 4, "6d10", 5, "7d10", 6, "8d10", 7, "9d10", 8, "10d10", 9, "11d10"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    INSECT_PLAGUE("Insect Plague", 5, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(5, "4d10", 6, "5d10", 7, "6d10", 8, "7d10", 9, "8d10"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    INSTANT_SUMMONS("Instant Summons", 6, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    INVISIBILITY("Invisibility", 2, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    IRRESISTIBLE_DANCE("Irresistible Dance", 5, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2024), List.of(ComponentEnum.V)),
    JUMP("Jump", 1, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    KNOCK("Knock", 2, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    LEGEND_LORE("Legend Lore", 5, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    LEMUNDS_TINY_HUT("Leomund's Tiny Hut", 3, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    LEOMUNDS_SECRET_CHEST("Leomund's Secret Chest", 4, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    LESSER_RESTORATION("Lesser Restoration", 2, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    LEVITATE("Levitate", 2, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    LIGHT("Light", 0, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    LIGHTNING_ARROW("Lightning Arrow", 3, MagicSchool.EVOCATION, DamageEnum.LIGHTNING, Map.of(3, "4d8 + 4d6", 4, "5d8 + 4d6", 5, "6d8 + 4d6", 6, "7d8 + 4d6", 7, "8d8 + 4d6", 8, "9d8 + 4d6", 9, "10d8 + 4d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    LIGHTNING_BOLT("Lightning Bolt", 3, MagicSchool.EVOCATION, DamageEnum.LIGHTNING, Map.of(3, "8d6", 4, "9d6", 5, "10d6", 6, "11d6", 7, "12d6", 8, "13d6", 9, "14d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    LOCATE_ANIMALS_OR_PLANTS("Locate Animals or Plants", 2, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    LOCATE_CREATURE("Locate Creature", 4, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    LOCATE_OBJECT("Locate Object", 2, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    LONGSTRIDER("Longstrider", 1, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MAGE_ARMOR("Mage Armor", 1, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MAGE_HAND("Mage Hand", 0, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MAGIC_CIRCLE("Magic Circle", 3, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MAGIC_JAR("Magic Jar", 6, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MAGIC_MISSILE("Magic Missile", 1, MagicSchool.EVOCATION, DamageEnum.FORCE, Map.of(1, "1d4 + 1", 2, "1d4 + 1", 3, "1d4 + 1", 4, "1d4 + 1", 5, "1d4 + 1", 6, "1d4 + 1", 7, "1d4 + 1", 8, "1d4 + 1", 9, "1d4 + 1"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MAGIC_MOUTH("Magic Mouth", 2, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MAGIC_WEAPON("Magic Weapon", 2, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MAGNIFICENT_MANSION("Magnificent Mansion", 7, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MAJOR_IMAGE("Major Image", 3, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MASS_CURE_WOUNDS("Mass Cure Wounds", 5, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MASS_HEAL("Mass Heal", 9, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MASS_HEALING_WORD("Mass Healing Word", 3, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MASS_SUGGESTION("Mass Suggestion", 6, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MAZE("Maze", 8, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MELD_INTO_STONE("Meld Into Stone", 3, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MELFS_ACID_ARROW("Melf's Acid Arrow", 2, MagicSchool.EVOCATION, DamageEnum.ACID, Map.of(2, "4d4", 3, "5d4", 4, "6d4", 5, "7d4", 6, "8d4", 7, "9d4", 8, "10d4", 9, "11d4"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    MENDING("Mending", 0, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MESSAGE("Message", 0, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    METEOR_SWARM("Meteor Swarm", 9, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(9, "20d6 + 20d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MIND_BLANK("Mind Blank", 8, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MINOR_ILLUSION("Minor Illusion", 0, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MIRAGE_ARCANE("Mirage Arcane", 7, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MIRROR_IMAGE("Mirror Image", 2, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MISLEAD("Mislead", 5, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MISTY_STEP("Misty Step", 2, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MODIFY_MEMORY("Modify Memory", 5, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MOONBEAM("Moonbeam", 2, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(2, "2d10", 3, "3d10", 4, "4d10", 5, "5d10", 6, "6d10", 7, "7d10", 8, "8d10", 9, "9d10"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    MORDENKAINENS_FAITHFUL_HOUND("Mordenkainen's Faithful Hound", 4, MagicSchool.CONJURATION, DamageEnum.POISON, Map.of(4, "4d8", 5, "5d8", 6, "6d8", 7, "7d8", 8, "8d8", 9, "9d8"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    MORDENKAINENS_MAGNIFICENT_MANSION("Mordenkainen's Magnificent Mansion", 7, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    MORDENKAINENS_PRIVATE_SANCTUM("Mordenkainen's Private Sanctum", 4, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    MORDENKAINENS_SWORD("Mordenkainen's Sword", 7, MagicSchool.EVOCATION, DamageEnum.FORCE, Map.of(7, "3d10 + MOD", 8, "4d10 + MOD", 9, "5d10 + MOD"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    MOVE_EARTH("Move Earth", 6, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    NONDETECTION("Nondetection", 3, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    NYSTULS_MAGIC_AURA("Nystul's Magic Aura", 2, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    OTILUKES_FREEZING_SPHERE("Otiluke's Freezing Sphere", 6, MagicSchool.EVOCATION, DamageEnum.COLD, Map.of(6, "10d6", 7, "11d6", 8, "12d6", 9, "13d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    OTILUKES_RESILIENT_SPHERE("Otiluke's Resilient Sphere", 4, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    OTTOS_IRRESISTIBLE_DANCE("Otto's Irresistible Dance", 6, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    PASSWALL("Passwall", 5, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PASS_WITHOUT_TRACE("Pass Without Trace", 2, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PHANTASMAL_FORCE("Phantasmal Force", 2, MagicSchool.ILLUSION, DamageEnum.PSYCHIC, Map.of(2, "1d6", 3, "2d6", 4, "3d6", 5, "4d6", 6, "5d6", 7, "6d6", 8, "7d6", 9, "8d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    PHANTASMAL_KILLER("Phantasmal Killer", 4, MagicSchool.ILLUSION, DamageEnum.PSYCHIC, Map.of(4, "4d10"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PHANTOM_STEED("Phantom Steed", 3, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PLANAR_ALLY("Planar Ally", 6, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PLANAR_BINDING("Planar Binding", 5, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PLANE_SHIFT("Plane Shift", 7, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PLANT_GROWTH("Plant Growth", 3, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    POISON_SPRAY("Poison Spray", 0, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    POLYMORPH("Polymorph", 4, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    POWER_WORD_HEAL("Power Word Heal", 9, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    POWER_WORD_KILL("Power Word Kill", 9, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    POWER_WORD_STUN("Power Word Stun", 8, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PRAYER_OF_HEALING("Prayer of Healing", 2, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PRESTIDIGITATION("Prestidigitation", 0, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PRISMATIC_SPRAY("Prismatic Spray", 7, MagicSchool.EVOCATION, null, Map.of(7, "10d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PRISMATIC_WALL("Prismatic Wall", 9, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PRIVATE_SANCTUM("Private Sanctum", 4, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PRODUCE_FLAME("Produce Flame", 0, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PROGRAMMED_ILLUSION("Programmed Illusion", 6, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PROJECT_IMAGE("Project Image", 7, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PROTECTION_FROM_ENERGY("Protection From Energy", 3, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PROTECTION_FROM_EVIL_AND_GOOD("Protection from Evil and Good", 1, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PROTECTION_FROM_POISON("Protection from Poison", 2, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    PURIFY_FOOD_AND_DRINK("Purify Food and Drink", 1, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    RAISE_DEAD("Raise Dead", 5, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    RARYS_TELEPATHIC_BOND("Rary's Telepathic Bond", 5, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    RAY_OF_ENFEEBLEMENT("Ray of Enfeeblement", 2, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    RAY_OF_FROST("Ray of Frost", 0, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    RAY_OF_SICKNESS("Ray of Sickness", 1, MagicSchool.NECROMANCY, DamageEnum.POISON, Map.of(1, "2d8", 2, "3d8", 3, "4d8", 4, "5d8", 5, "6d8", 6, "7d8", 7, "8d8", 8, "9d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    REGENERATE("Regenerate", 7, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    REINCARNATE("Reincarnate", 5, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    REMOVE_CURSE("Remove Curse", 3, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    RESILIENT_SPHERE("Resilient Sphere", 4, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    RESISTANCE("Resistance", 0, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    RESURRECTION("Resurrection", 7, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    REVERSE_GRAVITY("Reverse Gravity", 7, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    REVIVIFY("Revivify", 3, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    ROPE_TRICK("Rope Trick", 2, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SACRED_FLAME("Sacred Flame", 0, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SANCTUARY("Sanctuary", 1, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SCORCHING_RAY("Scorching Ray", 2, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(2, "2d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SCRYING("Scrying", 5, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SEARING_SMITE("Searing Smite", 1, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(1, "1d6", 2, "2d6", 3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    SECRET_CHEST("Secret Chest", 4, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SEEMING("Seeming", 5, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SEE_INVISIBILITY("See Invisibility", 2, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SENDING("Sending", 3, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SEQUESTER("Sequester", 7, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SHAPECHANGE("Shapechange", 9, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SHATTER("Shatter", 2, MagicSchool.EVOCATION, DamageEnum.THUNDER, Map.of(2, "3d8", 3, "4d8", 4, "5d8", 5, "6d8", 6, "7d8", 7, "8d8", 8, "9d8", 9, "10d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SHIELD("Shield", 1, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SHIELD_OF_FAITH("Shield of Faith", 1, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SHILLELAGH("Shillelagh", 0, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SHOCKING_GRASP("Shocking Grasp", 0, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SILENCE("Silence", 2, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SILENT_IMAGE("Silent Image", 1, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SIMULACRUM("Simulacrum", 7, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SLEEP("Sleep", 1, MagicSchool.ENCHANTMENT, null, Map.of(1, "5d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SLEET_STORM("Sleet Storm", 3, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SLOW("Slow", 3, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SPARE_THE_DYING("Spare the Dying", 0, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SPEAK_WITH_ANIMALS("Speak with Animals", 1, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SPEAK_WITH_DEAD("Speak with Dead", 3, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SPEAK_WITH_PLANTS("Speak with Plants", 3, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SPIDER_CLIMB("Spider Climb", 2, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SPIKE_GROWTH("Spike Growth", 2, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SPIRITUAL_WEAPON("Spiritual Weapon", 2, MagicSchool.EVOCATION, DamageEnum.FORCE, Map.of(2, "1d8 + MOD", 3, "1d8 + MOD", 4, "2d8 + MOD", 5, "2d8 + MOD", 6, "3d8 + MOD", 7, "3d8 + MOD", 8, "4d8 + MOD", 9, "4d8 + MOD"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SPIRIT_GUARDIANS("Spirit Guardians", 3, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    STAGGERING_SMITE("Staggering Smite", 4, MagicSchool.EVOCATION, DamageEnum.PSYCHIC, Map.of(4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    STINKING_CLOUD("Stinking Cloud", 3, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    STONESKIN("Stoneskin", 4, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    STONE_SHAPE("Stone Shape", 4, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    STORM_OF_VENGEANCE("Storm of Vengeance", 9, MagicSchool.CONJURATION, DamageEnum.THUNDER, Map.of(9, "2d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SUGGESTION("Suggestion", 2, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SUNBEAM("Sunbeam", 6, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(6, "6d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SUNBURST("Sunburst", 8, MagicSchool.EVOCATION, DamageEnum.RADIANT, Map.of(8, "12d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    SWIFT_QUIVER("Swift Quiver", 5, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    SYMBOL("Symbol", 7, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TASHA_HIDEOUS_LAUGHTER("Tasha's Hideous Laughter", 1, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    TELEKINESIS("Telekinesis", 5, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TELEPATHIC_BOND("Telepathic Bond", 5, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TELEPATHY("Telepathy", 8, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    TELEPORT("Teleport", 7, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TELEPORTATION_CIRCLE("Teleportation Circle", 5, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TENSERS_FLOATING_DISC("Tenser's Floating Disc", 1, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    THAUMATURGY("Thaumaturgy", 0, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    THORN_WHIP("Thorn Whip", 0, MagicSchool.EVOCATION, DamageEnum.PIERCING, Map.of(0, "1d6", 1, "2d6", 2, "3d6", 3, "4d6", 4, "5d6", 5, "6d6", 6, "7d6", 7, "8d6", 8, "9d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    THUNDEROUS_SMITE("Thunderous Smite", 1, MagicSchool.EVOCATION, DamageEnum.THUNDER, Map.of(1, "2d6", 2, "3d6", 3, "4d6", 4, "5d6", 5, "6d6", 6, "7d6", 7, "8d6", 8, "9d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    THUNDERWAVE("Thunderwave", 1, MagicSchool.EVOCATION, DamageEnum.THUNDER, Map.of(1, "2d8", 2, "3d8", 3, "4d8", 4, "5d8", 5, "6d8", 6, "7d8", 7, "8d8", 8, "9d8", 9, "10d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TIME_STOP("Time Stop", 9, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TINY_HUT("Tiny Hut", 3, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TONGUES("Tongues", 3, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TRANSPORT_VIA_PLANTS("Transport via Plants", 6, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TRAP_THE_SOUL("Trap the Soul", 8, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    TREE_STRIDE("Tree Stride", 5, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TRUE_POLYMORPH("True Polymorph", 9, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TRUE_RESURRECTION("True Resurrection", 9, MagicSchool.NECROMANCY, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TRUE_SEEING("True Seeing", 6, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TRUE_STRIKE("True Strike", 0, MagicSchool.DIVINATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    TSUNAMI("Tsunami", 8, MagicSchool.EVOCATION, DamageEnum.BLUDGEONING, Map.of(8, "12d10"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    UNSEEN_SERVANT("Unseen Servant", 1, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    VAMPIRIC_TOUCH("Vampiric Touch", 3, MagicSchool.NECROMANCY, DamageEnum.NECROTIC, Map.of(3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    VICIOUS_MOCKERY("Vicious Mockery", 0, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WALL_OF_FIRE("Wall of Fire", 4, MagicSchool.EVOCATION, DamageEnum.FIRE, Map.of(4, "5d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WALL_OF_FORCE("Wall of Force", 5, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WALL_OF_ICE("Wall of Ice", 6, MagicSchool.EVOCATION, DamageEnum.COLD, Map.of(6, "10d6", 7, "12d6", 8, "14d6", 9, "16d6"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WALL_OF_STONE("Wall of Stone", 5, MagicSchool.EVOCATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WALL_OF_THORNS("Wall of Thorns", 6, MagicSchool.CONJURATION, DamageEnum.PIERCING, Map.of(6, "7d8", 7, "8d8", 8, "9d8", 9, "10d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WARDING_BOND("Warding Bond", 2, MagicSchool.ABJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WATER_BREATHING("Water Breathing", 3, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WATER_WALK("Water Walk", 3, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WEB("Web", 2, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WEIRD("Weird", 9, MagicSchool.ILLUSION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WIND_WALK("Wind Walk", 6, MagicSchool.TRANSMUTATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WIND_WALL("Wind Wall", 3, MagicSchool.EVOCATION, DamageEnum.BLUDGEONING, Map.of(3, "3d8"), List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WISH("Wish", 9, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WITCH_BOLT("Witch Bolt", 1, MagicSchool.EVOCATION, DamageEnum.LIGHTNING, Map.of(1, "1d12", 2, "2d12", 3, "3d12", 4, "4d12", 5, "5d12", 6, "6d12", 7, "7d12", 8, "8d12", 9, "9d12"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    WORD_OF_RECALL("Word of Recall", 6, MagicSchool.CONJURATION, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V)),
    WRATHFUL_SMITE("Wrathful Smite", 1, MagicSchool.EVOCATION, DamageEnum.PSYCHIC, Map.of(1, "1d6", 2, "2d6", 3, "3d6", 4, "4d6", 5, "5d6", 6, "6d6", 7, "7d6", 8, "8d6", 9, "9d6"), List.of(VersionEnum.V2014), List.of(ComponentEnum.V)),
    ZONE_OF_TRUTH("Zone of Truth", 2, MagicSchool.ENCHANTMENT, null, null, List.of(VersionEnum.V2014, VersionEnum.V2024), List.of(ComponentEnum.V));

    private final String name;
    private final int level;
    private final MagicSchool school;
    private final DamageEnum damageType;
    private final Map<Integer, String> damageAtSlotLevel;
    private final List<VersionEnum> versions;
    private final List<ComponentEnum> components;

    SpellEnum(String name, int level, MagicSchool school, DamageEnum damageType, Map<Integer, String> damageAtSlotLevel, List<VersionEnum> versions, List<ComponentEnum> components) {
        this.name = name;
        this.level = level;
        this.school = school;
        this.damageType = damageType;
        this.damageAtSlotLevel = damageAtSlotLevel;
        this.versions = versions;
        this.components = components;
    }

    public Spell toSpell() {
        return new Spell(this.name(), this.name(), level, school, damageType, damageAtSlotLevel != null ? damageAtSlotLevel.toString() : "");
    }

    public Spell toSpell(Integer npcLevel) {
        return new Spell(this.name(), this.name(), level, school, damageType, getDamageForLevel(damageAtSlotLevel, npcLevel));
    }

    private String getDamageForLevel(Map<Integer, String> damageAtSlotLevel, Integer npcLevel) {
        if (damageAtSlotLevel == null || npcLevel == null) return "";
        for (int lvl = npcLevel; lvl >= 0; lvl--) {
            if (damageAtSlotLevel.containsKey(lvl)) {
                return damageAtSlotLevel.get(lvl);
            }
        }
        return "";
    }
}
