spring:
  application:
    name: dnd

  web:
    resources:
      add-mappings: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

  mongodb:
    uri: mongodb+srv://raphatorres89:31ZlM6Nmtd2Y1xQi@dndspirit.yhqescd.mongodb.net/dnd?authSource=admin&appName=DnDSpirit

server:
  servlet:
    session:
      cookie:
        secure: true # em produção com https

patreon:
  client-id: ${PATREON_CLIENT_ID}
  client-secret: ${PATREON_CLIENT_SECRET}
  redirect-uri: ${PATREON_REDIRECT_URI}
  webhook:
    secret: ${PATREON_WEBHOOK_SECRET}