spring:
  application:
    name: dnd

  web:
    resources:
      add-mappings: true

  datasource:
    url: jdbc:postgresql://localhost:5432/dnd
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

server:
  servlet:
    session:
      cookie:
        secure: true # em produção com https

patreon:
  client-id: ${PATREON_CLIENT_ID}
  client-secret: ${PATREON_CLIENT_SECRET}
  redirect-uri: ${PATREON_REDIRECT_URI}
  webhook:
    secret: ${PATREON_WEBHOOK_SECRET}